### ISSUE TITLE
Implement Offset Commit/Fetch API

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/pykafka#114]
This needs to be implemented in protocol.py and in any relevant objects.

  - [x] Implement wire protocol in protocol.py
  - [x] Add offset commit/fetch functionality to Broker
  - [x] Finish SimpleConsumer implementation, Issue #115.
  - [x] Add offset commit/fetch to SimpleConsumer
  - [x] Protocol unit tests

**Comment by yungchin** [comment]
(I'm just adding a librdkafka label for now, because I'll be tracking your design work on a offset fetch/commit api. There's still some work to do on this in python-librdkafka as well, which for now I'll be tracking at https://bitbucket.org/yungchin/python-librdkafka/issue/7 )

**Comment by emmett9001** [comment]
In progress [here](https://github.com/Parsely/pykafka/pull/136)

**Comment by emmett9001** [comment]
Implemented all API requests and responses under [this section](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommit/FetchAPI). There are still two response tests that I can't get decent test data for.

**Comment by emmett9001** [comment]
Turns out that this is correct and we should clear up the name differences between the "Offset API" and the "Offset Commit/Fetch API". We need one term for committing and fetching actual offsets - for this, I think `commit_offset` and `fetch_offset` make sense. We also need a term for fetching earliest and latest offsets - perhaps `fetch_offset_range` and `fetch_offset_bound` make sense here.

**Comment by kbourgoin** [comment]
:+1:

**Comment by emmett9001** [comment]
I've added the offset management functionality to the SimpleConsumer and tested it against my local kafka instance. As far as I'm concerned this ticket is done.
