### ISSUE TITLE
reset_offsets_on_start doesn't affect all partitions

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#168]
Against Parsely's 100-partition topic, starting 20 `BalancedConsumers` simultaneously with `reset_offsets_on_start=True` results in a few (6-10) partitions not having their offsets reset to `OFFSET_LATEST`.

**Comment by emmett9001** [comment]
[This](https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L425-L434) could probably stand to be in a retry loop.

**Comment by kbourgoin** [comment]
I just had this happen to me as well. Could it be a race condition when there are a whole bunch of consumers starting at the same time?

I'm also pretty sure that resetting to latest didn't work since I created what I think is a new consumer group and instead of starting on latest, it started at 0.  It might be a different issue or the same.  I'll do more investigation next week into what happened.
