### ISSUE TITLE
WARNING:kazoo.client:Connection dropped: socket connection error: Connection refused

### ISSUE THREAD

**Issue by jvalentini** [Parsely/pykafka#182]
Hi, 

I'm currently using kafka-python but looking at switching to pykafka. However, trying to consume messages from my existing kafka cluster is producing the following error when using pykafka:

`WARNING:kazoo.client:Connection dropped: socket connection error: Connection refused`

My guess is that this something related to firewall rules but I don't really understand what's going on to effectively debug the problem.

I *think* I'm able to connect to the kafka brokers without issue because I'm able to print out a list of topics from the cluster. It's only when I try to consume messages from a topic that I get the error above.

Can anyone explain what's going on behind the scenes here? Assuming it does connect to the brokers successfully, what happens after that? Where does Zookeeper come into play?

Thanks in advance!

**Comment by emmett9001** [comment]
I assume you're using a `BalancedConsumer`, since the `SimpleConsumer` doesn't communicate with ZooKeeper at all. The `BalancedConsumer` can be started without communicating with ZooKeeper if `auto_start=False`, but it defaults to `True`. My initial guess was that your machine is unable to communicate with the ZooKeeper cluster you're telling it to talk to, but if that were the case I believe you'd see this error immediately upon starting the consumer.

You do need to specify the location of your ZooKeeper cluster in the `BalancedConsumer` `__init__` function using the `zookeeper_connect` kwarg.

Is there any code you can share to give more information?

**Comment by jvalentini** [comment]
Thanks for the response, @emmett9001.

This is completely my fault. The issue is that I never set the `zookeeper_connect` kwarg. I was reading the "Getting Started" section of the docs and it didn't mention that flag like it does for KafkaClient's hosts kwarg, so I didn't realize it was necessary. Maybe it would be helpful to add that to the docs?

Either way, thank you for the assistance!

**Comment by emmett9001** [comment]
Thanks @jvalentini for pointing out that oversight in the readme. I've fixed it so it's clearer for future users.

**Comment by jvalentini** [comment]
You're awesome! :+1:
