### ISSUE TITLE
Manually Set Offsets in Consumers

### ISSUE THREAD

**Issue by zhynxn** [Parsely/pykafka#187]
Hello, 
I have question about set offset for consumer-group on partition. 
I know there is auto_offset_reset parameter to reset the offset to LATEST or EARLIEST when OffsetOutOfRangeError happens. It is really helpful. 

My question is can I manually set specific offset number for consumer-group, partition? So I can do more error handling in my own program. 

There is such function in kafka-python package (http://kafka-python.readthedocs.org/en/latest/apidoc/kafka.consumer.html) 

Please let me know. 
Thanks,
Yanxin 

set_topic_partitions(*topics)
Set the topic/partitions to consume Optionally specify offsets to start from

Accepts types:

str (utf-8): topic name (will consume all available partitions)
tuple: (topic, partition)
dict:
{ topic: partition }
{ topic: [partition list] }
{ topic: (partition tuple,) }
Optionally, offsets can be specified directly:

tuple: (topic, partition, offset)
dict: { (topic, partition): offset, ... }

**Comment by yungchin** [comment]
Hi Yanxin,

I'm currently using something like `consumer._partitions_by_id[partition_id].set_offset(offset)` to do this, but I suppose that feels like using what is a semi-public interface at best. It would probably be good to get @emmett9001's advice on this too.

**Comment by emmett9001** [comment]
The `SimpleConsumer` currently doesn't directly support starting consumption from an arbitrary offset. You can only start from `OFFSET_EARLIEST` or `OFFSET_LATEST`. @yungchin is correct that it's possible to adjust the current offset of the consumer with `consumer._partitions_by_id[partition_id].set_offset(offset)`, but this method has two problems. First, you have to make this call after instantiating the consumer or your offset changes will be overwritten. Second, it's a private method that isn't really meant to be used externally.

This is a feature that's worth adding, so I'll add this to the next release milestone.

**Comment by yungchin** [comment]
Can I add two related feature requests here for discussion?

I suppose a big use case for this feature is that people store their offsets outside of kafka. For that use case, in addition to manually setting, it would be nice to have a simple interface for getting offsets out of the consumer (this is different from `fetch_offsets` which gets them from kafka). I think this code in tests might be good enough for that? https://github.com/Parsely/pykafka/blob/24c364527012fe0768e2c6addc19be9990f3c1f6/tests/pykafka/test_simpleconsumer.py#L67

And, second, for this use case it would be good to have a third OffsetType, maybe named OffsetType:EXCEPTION or such, which would simply allow OffsetOutOfRangeError to bubble up to the application layer, rather than triggering a reset. That would let the user know that their external offset store needs checking.

Happy to work on either of those, if we think it's a good idea.

**Comment by emmett9001** [comment]
An interface for getting offsets held by the consumer is a good idea in general. I'm not totally sure about the `OffsetOutOfRangeError` idea. When exactly would this `EXCEPTION` type become visible to the client? `OffsetOutOfRangeError` is raised during `fetch` and `commit_offsets`, both of which are usually called automatically on separate threads. Also, we'd have to include some config option to turn off automatic offset resetting, like `reset_offset_on_range_error`.

**Comment by yungchin** [comment]
Hmmm yeah - I'm not sure what would be an elegant way to implement the `OffsetType` idea - especially getting it out of the worker thread after you do a `fetch` is bound to be ugly I guess. Maybe, only if this option is set, send an extra request upon `start` to see if that raises `OffsetOutOfRangeError`? That's of course ugly too, but...

It would just be really convenient from a user perspective: instead of having to either parse the logs for a reset_offsets event, or reading out consumed message offsets to see that they jumped to earliest/latest, you could just start with something like

``` python
try:
    topic.get_simple_consumer(auto_offset_reset=OffsetType.EXCEPT, ...)
except OffsetOutOfRangeError:
    do_stuff_to_repair_external_offset_store()
```

**Comment by emmett9001** [comment]
@zhynxn I've merged a fix for this into master. The new method of manually setting offsets in the consumer is as follows:

```python
consumer = topic.get_simple_consumer(consumer_group="testgroup")
partition_offset_pairs = [(p, get_offset_for_partition(p)) for p in consumer.partitions.itervalues()]
consumer.reset_offsets(partition_offsets=partition_offset_pairs)
```

**Comment by coffenbacher** [comment]
What is get_offset_for_partition? I can write what is probably an equivalent, but it doesn't seem to be defined anywhere on the internet

**Comment by yungchin** [comment]
@coffenbacher: yup! Thanks.

**Comment by emmett9001** [comment]
@rueberger per the [docs](http://pykafka.readthedocs.io/en/latest/api/simpleconsumer.html#pykafka.simpleconsumer.SimpleConsumer.reset_offsets), `reset_offsets` doesn't require a special type, just a sequence of `(pykafka.partition.Partition, int)` tuples. As noted in https://github.com/Parsely/pykafka/issues/830, the internal logic of `reset_offsets` very likely needs to be updated, or at the very least evaluated for correctness. I agree that treating the given integers as timestamps before offsets is a little weird, and I'm going to see if there's a way around this given my recently deepened understanding of the Offsets API.

If memory serves, the timestamp information for a given message should be available via `Message.timestamp` if the Kafka version being used supports it.

**Comment by rueberger** [comment]
Thanks for looking into this @emmett9001. 

For posterity's sake, much of my confusion about timestamps stemmed from using an older version of `kafka` without timestamp support in my initial digging. After upgrading `kafka`and setting the `broker_version` kwarg in `pykafka.KafkaClient.__init__`  things made sense.

**Comment by emmett9001** [comment]
I'm glad you were able to discover that procedure via the available documentation. Any thoughts or PRs on how to improve the process of discovering that information are quite welcome.
