### ISSUE TITLE
Is that possible to know which partition the message is from?

### ISSUE THREAD

**Issue by fortime** [Parsely/pykafka#199]
I want to log the offset and partition id If a process handled a mesaage failed. So I can use the log to redo those messages.
It seems like we can get the partition id after scanning the source code. Can you guys add a field in message to save the partition id?

**Comment by emmett9001** [comment]
Hi @fortime. It's not clear to me where exactly you need access to the partition ID. Are you talking about the producer or the consumer?

**Comment by fortime** [comment]
@emmett9001 the consumer

**Comment by emmett9001** [comment]
@fortime After checking out other implementations of this feature, it does seem like something worth adding to pykafka. It turns out it's not trivial though, so I'll be putting in a pull request for the refactor that enables this in the next few weeks. Unfortunately there's no workaround at the moment. Thanks for helping improve pykafka!

**Comment by emmett9001** [comment]
@fortime This actually ended up being easier than I expected, and I've committed it to master https://github.com/Parsely/pykafka/commit/a4b8d95bb63dd9bb99cb784034c4b13deaeb4a58 . You can get the partition that generated a message by examining `message.partition` and `message.partition_id`.

**Comment by fortime** [comment]
@emmett9001 Thanks! When will this feature be on pip?

**Comment by emmett9001** [comment]
@fortime I just uploaded it! https://pypi.python.org/pypi/pykafka/1.1.0

**Comment by fortime** [comment]
@emmett9001 Great!
