### ISSUE TITLE
How to use pykafka connect zookeeper and kafka

### ISSUE THREAD

**Issue by zbing3** [Parsely/pykafka#200]
Hi all:
We used zookeeper and kafka Cluster, How to use pykafka connect zookeeper and kafka?

**Comment by emmett9001** [comment]
Hi @zbing3 - please see the `BalanacedConsumer` [example](http://pykafka.readthedocs.org/en/latest/) in the documentation for an illustration of how to use zookeeper with pykafka.

You can use the `zookeeper_connect` kwarg on `BalancedConsumer` to specify a set of zookeeper nodes to which to connect.
```python
balanced_consumer = topic.get_balanced_consumer(
    consumer_group='testgroup',
    auto_commit_enable=True,
    zookeeper_connect='myZkClusterNode1.com:2181,myZkClusterNode2.com:2181/myZkChroot'
)
```
If you're using the `SimpleConsumer`, you actually don't need to use zookeeper at all, since `SimpleConsumer` stores its offset information in kafka. pykafka only requires a zookeeper connection when using the `BalancedConsumer`.

If you have other questions about pykafka usage, you can send them to the pykafka mailing list: pykafka-user%40googlegroups.com

**Comment by zbing3** [comment]
thx~
