### ISSUE TITLE
Starting > 1 consumer hangs python process

### ISSUE THREAD

**Issue by Fluxx** [Parsely/pykafka#218]
Using `pykafka==1.1.0`, running against a single node Kafka `0.8.2.1` server, the following script hang and never exits:

```python
from pykafka import KafkaClient


client = KafkaClient('kafka:9092')

consumer1 = client.topics['test1'].get_simple_consumer()
consumer2 = client.topics['test2'].get_simple_consumer()

print 'Consumers made'
```

Running I see this:

```bash
$ python application consumertest.py
Consumers made
```

And the process seems to hang forever.  I have waited as long as 5 minutes and it never exits.

For some more evidence, if I change the consumer constructor to `get_simple_consumer(auto_start=False)` the script exits, however, if I then add this code below...

```python
consumer1.start()
consumer2.start()
```

...the process hangs again, leaving me to think somewhere in the `consumer.start()` process is where the issue is.  Finally, when hanging, if I `SIGTERM` Kafka the Python process exits without any exception being thrown.

I'm about to start digging into the `start()` code to see if I can track down the issue myself, but I wanted to post this here in case this is a known issue (I couldn't find any) or if you guys had a better idea what might be going on here?

**Comment by Fluxx** [comment]
Hmmm....more info.  If I change the [sleep in the fetch worker](https://github.com/Parsely/pykafka/blob/1.1.0/pykafka/simpleconsumer.py#L278) to `0.1` Python exits just fine.  Also if comment out [the `fetch_lock.release()`](https://github.com/Parsely/pykafka/blob/1.1.0/pykafka/simpleconsumer.py#L607) as part of fetching new messages, Python also exits too.  Not 100% sure what this means, but I'll keep digging.

**Comment by emmett9001** [comment]
A simple workaround for this is calling `consumer1.stop(); consumer2.stop()` when you'd like your program to exit. This ensures clean shutdown of the worker threads used in message fetching.

**Comment by Fluxx** [comment]
@emmett9001 thanks for the quick reply and suggestion, that certainly works.  I'm stumped as to why this is happening in the first place though as the threads started all all daemon threads so they shouldn't hang like this...so weird.

**Comment by emmett9001** [comment]
My thoughts exactly. This will require some digging.

**Comment by Fluxx** [comment]
Sounds good.  Happy to help debug if needed.

**Comment by emmett9001** [comment]
Any further information you can provide on possible causes is really appreciated.

**Comment by emmett9001** [comment]
This bug still exists in `2.0.0`

**Comment by emmett9001** [comment]
Some facts:

* Changing the fetcher thread sleep interval to `1` fixes the issue
* Producing to the topic while the consumers are running sometimes fixes the issue
* Logging in `fetch()` sometimes fixes the issue

**Comment by emmett9001** [comment]
I have a hunch that this is happening because the two consumers are sharing the same `Broker` objects, in particular the same `_req_handler` thread for each broker.

**Comment by emmett9001** [comment]
Looks like I figured it out. The two consumers were effectively not locking their partitions for fetching, since each consumer was using its own lock per partition. The fix just has the consumers share the same lock for each partition so that the locking logic actually works.

**Comment by yungchin** [comment]
I was just doing some print debugging which suggests that it hangs [at this line][0] (which I presume gets called via `atexit` [here][1]). I don't know why that `Queue.join()` hangs, possibly because the consumers fail to die and keep filling it with more requests? But if that's the case, I also don't get why it takes two consumers to make this block - maybe because one cannot fill the queue fast enough to keep it from `join`ing?

More questions than answers I'm afraid...

(I've certainly had no luck so far to ever get `SimpleConsumer.__del__` to run if I hadn't called `SimpleConsumer.stop` before, which plays into this - the result is that those worker threads always die in a fire at program exit. I remember mentioning at some point that I tried to plug in `weakref`s all over the place, but that still didn't make `__del__` run.)

[0]: https://github.com/Parsely/pykafka/blob/e5d2df2193e30c7c4c0d35e8ff380f3268ba2c76/pykafka/handlers.py#L123
[1]: https://github.com/Parsely/pykafka/blob/e5d2df2193e30c7c4c0d35e8ff380f3268ba2c76/pykafka/handlers.py#L100

**Comment by yungchin** [comment]
(PS: I guess all the various ways you listed that make the hangs go away all have in common that they slow down the rate of fetching - so that's sort of consistent with this?)

**Comment by emmett9001** [comment]
Yes, but they're daemon threads. I'm not aware of the generalized case in which two daemon threads can do anything that causes the main thread to block like this. My basic insight is that for this to be happening, the threads *must* be sharing some resource. I found a resource that looked like a possible culprit, locked it, and the problem went away.

**Comment by yungchin** [comment]
No, I agree, I don't think there's a generalised case like that. What I'm surmising is that the fetcher threads don't get in each other's way at all, it's just that two consumers produce more requests than one. And the end result of that is, that the request queue never quite manages to get to `join`.

I'm quite certain that that `join` is where the main thread blocks: it's waiting for the fetch request queue to get to zero. [Here's](https://github.com/Parsely/pykafka/files/1695/diff.txt) my print debugging diff: if you run that with one consumer running, and try to exit the interpreter, you can see we enter `RequestHandler.stop` and then exit from it too. You'll also see that the consumer fetcher thread is still live while that happens.

When you run it with two live consumers, the enqueue rate is higher, and when you exit the interpreter you'll see it enter `RequestHandler.stop` but it never exits from there - the `Queue.join` never returns. So I'm not totally sure why that is, but my theory is it's just because the two fetcher threads keep hitting the queue with new requests fast enough.

So under that theory, the reason why the fix in #237 works is only that it makes the two consumers wait a lot, that is,  the locking slows the request rate down. That would be the same as why the longer `sleep` worked. I don't really like it as a solution, because it sacrifices performance when you have multiple consumers, for a problem that only exists at program exit.

[This](https://github.com/Parsely/pykafka/files/1696/diff.txt) is hackish fix based on that theory. It's not good, it makes for an ugly exit, but it shows that something similar might work.

**Comment by emmett9001** [comment]
Fixed in master [here](https://github.com/Parsely/pykafka/pull/258). @Fluxx, feel free to reopen if you're still able to replicate the bug on master, or make a new issue if you find anything else.

**Comment by Fluxx** [comment]
Thanks guys!  I'm in the middle of a different project right now, but I'll try to repro the issue a little later and let you know.
