### ISSUE TITLE
BalancedConsumer.consume() should block/fail during rebalance or if zk connection is pending/dead

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#273]
This comes out of #206. Clearly there are use cases where, if the zookeeper connection goes away and so you can't know if you still own your partitions, you should not be consuming from them. That's probably the safest option, ie to block/fail completely, and is what's the core of this commit (which would need redoing because it depends on a lot of other commits on that branch): https://github.com/Parsely/pykafka/commit/3b23fadeacfec18b91d22aaf121a349a329d02cc

**Comment by yungchin** [comment]
Note that https://github.com/Parsely/pykafka/commit/73e64bb42b42411812a96fc3458acedb97affe11 additionally proposed to kill the internal consumer - which I think makes sense because its auto-commit worker would otherwise still be writing to potentially "disowned" partitions.

**Comment by emmett9001** [comment]
From #274 

This was raised by @fortime in comments on #215: "The consumer will consume message during the time of rebalancing. It is an expected behavior, but it may cause messages in 30 seconds consumed by multiple consumers."

**Comment by amontalenti** [comment]
I just re-discovered this issue and the context for it, related to pull request #348.

So, here is my understanding of the crux of this issue:

- If two consumers are reading, in a balanced manner, from the same topic, and network access to ZK is lost for one of these consumers, if either consumer continues reading messages, it's possible that both consumers will read the same message. This is because a rebalance event could happen before either consumer knows about the change.
- The change @yungchin made here to raise a ZK disconnect exception upon immediate discovery of a downed ZK connection state puts the onus on the person writing a consumer: do you want to sleep until ZK comes online, or do you want to continue consuming messages but risk the possibility that two consumers might read the same message?
- The reason I reverted this change is because the side effect of the change is to make pykafka's typical consumer loop fail in the face of *any* network outage, for even milliseconds, when it seems that the right behavior (for resiliency, anyway) would seem to be to continue consuming messages until ZK comes back online

**Comment by amontalenti** [comment]
also for @emmett9001

**Comment by yungchin** [comment]
@amontalenti thanks for writing this out so clearly. It made me change my mind on this issue entirely: it was probably a completely misguided effort. My mistaken thinking here was that consumer rebalancing should aim to provide "exactly-once delivery", whereas actually kafka promises no such thing (and with this protocol, it can't really), and rather the objective is only "at-least-once delivery" (ie when a balanced consumer fails, another one picks up its partitions).

So I agree we should just continue to consume as long as we don't hear otherwise from ZK. To achieve this, we need to back out a bit more than #348 currently does. In fact we should probably revert most if not all of #317.
