### ISSUE TITLE
producer failure visibility

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#340]
Since the producer futures code was merged into master, any exception encountered by the producer during produce attempts is *only* accessible to client code via the futures interface. Specifically, [this code](https://github.com/Parsely/pykafka/blob/2b3a9f14880f20649b076da156c00a4aefc2e55a/pykafka/producer.py#L362-L365) used to raise an exception if a message had reached its maximum retry count. Now, it only sets that exception on the future. In practice, this means that client code that isn't using the futures interface will never see an exception indicating that their produce attempts have been failing.

I'm not entirely sure what the solution should be here, but felt like I should write this down. A nice effect of the old method was that producers would only ever run in a degraded state for a short period of time before failing completely. That is, when there aren't enough brokers up to satisfy the replication factor, the old method had the producer die after enough retries, where the new method only dies for clients not discarding the futures.

**Comment by yungchin** [comment]
Would it make sense to reinstate [the old exception raising code][0] when we detect that the future has been discarded? So basically if `ref is None`, raise?

I'm not sure if that's always the right solution though. Because basically it would say that you must check for delivery, or else we might abort your producer instance. Whereas some users may not care for delivery assurances, and want to just spray messages UDP style?

[0]: https://github.com/Parsely/pykafka/blob/1ced92485f2124dcd459c8c68e5d1154b6845a19/pykafka/producer.py#L343

**Comment by emmett9001** [comment]
That's a fair point. I guess the new plan to use a `Queue` instead of futures for error reporting will solve this, since it will give users who want to avoid producing to a subset of partitions a way to ensure that without impacting performance unduly. With the futures in place, users who want this guarantee have to take the performance hit associated with using futures.

**Comment by emmett9001** [comment]
Related to #344 and will probably close with it.
