### ISSUE TITLE
Allow grace period when BalancedConsumer detects failed ZK connection

### ISSUE THREAD

**Issue by yungchin** [Parsely/pykafka#346]
Currently, we immediately bail out when our zookeeper connection is pending or dead. On a laggy network that's annoying, because it means the user sees the BalancedConsumer die all the time. (Reported by @amontalenti.)

**Comment by amontalenti** [comment]
The way this looks:

```
Traceback (most recent call last):
  File "pykafka_consumer.py", line 91, in <module>
    tup = spout.next_tuple()
  File "pykafka_consumer.py", line 77, in next_tuple
    return self.emit_next()
  File "pykafka_consumer.py", line 59, in emit_next
    msg = self.consumer.consume()
  File "/home/am/.pyenv/versions/ist/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 715, in consume
    raise ZookeeperConnectionLost
pykafka.exceptions.ZookeeperConnectionLost
```

and, how the DEBUG logs look:

```
ARNING:kazoo.client:Connection dropped: outstanding heartbeat ping not received
WARNING:kazoo.client:Transition to CONNECTING
INFO:kazoo.client:Zookeeper connection lost
INFO:pykafka.balancedconsumer:zk_state_listener: SUSPENDED
INFO:kazoo.client:Connecting to z01.istresearch.com:2181
DEBUG:pykafka.balancedconsumer:Suspending internal consumer (tx220:4c915509-2717-48f8-be64-006867b83f47)
```

**Comment by amontalenti** [comment]
BTW, I was able to reproduce this using `ufw` port blocking from my client machine.

So, I:

1. spun up a pykafka consumer (single balanced consumer on 1 node).
2. ran `ufw reject out 2181` on my machine, and then reset my network interface to make the firewall rule take effect, because it didn't effect pykafka's established connection
3. almost instantly, the pykafka consumer lost connection with Zooekeeper and raised the `ZookeeperConnectionLost` exception

This made me realize that this exception simply shouldn't be raised at all. It's basically monitoring the ZK connection for the slightest outage (even ephemeral network outage or packet loss), and raising an exception that breaks the consumer thread instantly. I looked into the commits that added it with @rduplain and I don't see a good reason this custom exception type should be raised. So, I'm going to kill that exception from the code in a PR altogether.
