### ISSUE TITLE
overzealous LeaderNotAvailable

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#350]
[Here](https://github.com/Parsely/pykafka/blob/ac43c12b00578c7de22db8b080f6f2b3c2acdc10/pykafka/topic.py#L149), we throw `LeaderNotAvailable` in response to any `KeyError`. In fact, `KeyError` can happen in this function when it's a replica that's not available, not the leader. The former can still allow normal operation, the latter cannot.

**Comment by amontalenti** [comment]
I want to call attention to this code:

```python
try:
    for id_, meta in iteritems(p_metas):
        if meta.id not in self._partitions:
            log.debug('Adding partition %s/%s', self.name, meta.id)
            self._partitions[meta.id] = Partition(
                self, meta.id,
                brokers[meta.leader],
                [brokers[b] for b in meta.replicas],
                [brokers[b] for b in meta.isr],
            )
        else:
            self._partitions[id_].update(brokers, meta)
except KeyError:
    raise LeaderNotAvailable()
```

The issue I have here is that the `except KeyError` catches, by my count, 5 possible exceptions (at least, that I can see... excluding any function calls made within this code).

The behavior we're seeing is that LeaderNotAvailable() is thrown on any of these `KeyError`'s, and what's more, since the exception isn't chained, we don't know which one. I'm wondering if `brokers[meta.leader]` is giving a `KeyError` because `meta.leader` == -1 (and thus, no broker exists with that key), and that this explains the overzealousness of the exception. But, this is just a hunch. Could be any number of other conditions.

What's clear is that this exception catch is way too broad and needs to be tightened up quite a bit, with appropriate tests for the valid conditions. Although I don't have a broken cluster any longer to provide the precise state that caused this, I'll try to piece together the state from the bits and pieces of information I have.

**Comment by yungchin** [comment]
This is related to #338.

I was wondering if we're not better off checking `if PartitionMetadata.err == LeaderNotAvailable.ERROR_CODE` explicitly, rather than catching a `KeyError` if the leader is `-1`. I suppose we would still have to handle KeyErrors, because like you said metadata might hold replica IDs that we don't have an entry for in `Cluster.brokers`.

**Comment by emmett9001** [comment]
I've opened #355 to fix this issue. There are probably other cases in which we should be catching `KeyError`, but this change better reflects the initial intent behind the `try..catch`.
