### ISSUE TITLE
Python3 topic and group names must be bytes objects

### ISSUE THREAD

**Issue by kylebamos** [Parsely/pykafka#376]
In Python3, string startswith does not support bytes object arguments and bytes startswith does not support string object arguments.

Because of this, topic name strings given as a key to client.topics result in a traceback:

```
File "... /python3.4/site-packages/pykafka/cluster.py", line 141, in _should_exclude_topic
    return topic_name.startswith(b"__")
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

After passing the topic name as a bytes object instead, that issue stopped. Then other strangeness happened when attempting to get a balanced consumer from a topic with a specified consumer_group. When the consumer group was specified as a string object keyword argument to get_balanced_consumer, a NoPartitionsForConsumerException occurred. This was fixed by passing the consumer group as a bytes object as well.

**Comment by emmett9001** [comment]
Hi @kylebamos, thanks for checking this in. Please see [this comment](https://github.com/Parsely/pykafka/pull/246#issuecomment-136935797) explaining why these functions don't support python3 strings. Essentially it's a need for consistency across the entire public API with methods that send their inputs directly to kafka. Since we pass messages to kafka without encoding them according to any particular string encoding, we'd like the entire public API to behave consistently. I've also opened [this pull request](https://github.com/Parsely/pykafka/pull/377) to provide a clearer error message in these cases.

**Comment by yungchin** [comment]
Just a note, because I remember when we had that earlier discussion I couldn't find clear docs on what encodings are allowed in topic/group names. According to this it's a really limited set: https://issues.apache.org/jira/browse/KAFKA-495?focusedCommentId=13463303

    decided to ALLOW only ASCII alphanumeric characters and underscore and dash
