### ISSUE TITLE
Get consumer ends in infinite wait when process is spwaned using multiprocessing.Process

### ISSUE THREAD

**Issue by saran87** [Parsely/pykafka#388]
The `topic.get_simple_consumer()`  method call  got stuck in an infinite while loop at RequestHandler start_thread Line number [147](https://github.com/Parsely/pykafka/blob/6d730185e8dcaaf4502fe4c36ff9d8e9ae48a84d/pykafka/handlers.py#L147). When I tracked back the call-trace, this is happening while pykafka is trying to get the [offset manager](https://github.com/Parsely/pykafka/blob/fe6604e44c68b5af70525e74da19a0a2f04ed737/pykafka/cluster.py#L332). 

Below is the code that I was trying to execute. This code works perfectly when I use `threading.Thread`

```python
import logging as log
import time
import multiprocessing

from pykafka import KafkaClient
from pykafka.common import OffsetType

log.basicConfig(level=log.DEBUG)

client = KafkaClient(hosts="127.0.0.1:9092")


def run_consumer():
    topic = client.topics['test2']
    log.info("Got the topic")
    consumer = topic.get_simple_consumer("test")
    log.info("initialized consumer")
    consumer.start()
    time.sleep(2)

    while True:
        try:
            message = consumer.consume()
            if message:
                print message.value
        except:
            break


def run_consumers():
    t = multiprocessing.Process(target=run_consumer, name="consumer")
    t.daemon = False # True
    t.start()
    t.join()

if __name__ == "__main__":
    run_consumers()
```

**Comment by emmett9001** [comment]
Thanks @saran87. I dug deep into this and learned a few things. Consider this code:
```python
from threading import Thread
from multiprocessing import Process
import os

class MyThread(Thread):                                                                                                                                                      
    def __init__(self, *args, **kwargs):
        self.parent = current_thread()
        Thread.__init__(self, *args, **kwargs)

def run_thread():                                                                                                                                                                     
    print "in thread: {}".format(current_thread())
    print "in thread pid: {}".format(os.getpid())

def start_thread():
    t = MyThread(target=run_thread)
    t.start()
    print "parent: {}".format(t.parent)
    print "process thread: {}".format(current_thread())
    print "subprocess id: {}".format(os.getpid())
    t.join()

print "main process: {}".format(os.getpid())
p = Process(target=start_thread)                                                                                                                                                      
p.start()                                                                                                                                                                             
```
The output from this code surprised me:
```
main process: 4798
in thread: <MyThread(Thread-1, started 139802621290240)>
in thread pid: 5179
parent: <_MainThread(MainThread, started 139802680162048)>
subprocess id: 5179
process thread: <_MainThread(MainThread, started 139802680162048)>
```
This shows that the thread running on the child process being created is actually the same `Thread` instance as the main interpreter thread. This seems to imply that communicating between the main thread in which you've created your consumer instance and its worker threads amounts to interprocess communication. Specifically, communication between the `MyThread` instance and its parent thread (`_MainThread`) is also communication between process `5179` and process `4798`, since the latter is the original owner of `_MainThread`.

I'm not certain how sharing the main thread between the main process and a subprocess works (ie whether my theory above is valid), but the evidence seems to support it. My test code is essentially a simplified recreation of what you're doing in your code - spawning a child process, then running a consumer that makes its own threads. Since the consumer internally uses `Queue.Queue` to pass data between the main thread and child threads, it's not able to pass data between different processes (that's what `multiprocessing.Queue` is for). Attempts to implement a `ProcessHandler` that uses `multiprocessing.Queue` soon result in errors related to pickling.

As far as I can tell, PyKafka doesn't support subprocess execution for this reason. The current options are to use `threading.Thread` or to check out #368's gevent support.

**Comment by yungchin** [comment]
@saran87 just to add, while you can't use `multiprocessing` with pykafka in the way your example has it, you might be able to get most of what you want if you can afford having completely separate `KafkaClient` instances in each subprocess.

**Comment by saran87** [comment]
@yungchin yes, having completely separate `KafkaClient` works perfectly.
