### ISSUE TITLE
Q: BalancedConsummer's commit_offsets() does not prevent from message double reception? 

### ISSUE THREAD

**Issue by tigran-a** [Parsely/pykafka#389]
Hi, 

I've a balanced consumer that reads a flow from kafka.
At some point, e.g. every 1 second (for test purpose) I execute the code like:
```python
...
     consumer.consume() # note: non-blocking call, timeout 100ms
...
            if (time()-last_ts) >= 1:  # every second, for the example
                self.consumer.commit_offsets()
                self.consumer.stop() #?
                reconnected += 1
                log.warning("Recreating the consumer for the %d st/nd/th time", reconnected)
                self.connect(self.connect_retries)
                last_ts=time()
...
```
(i had to do it because of the failures when having long-running kafka consumer script) 

the self.connect looks like:
```python
        self.connect_retries = connect_retries
        ntries = 0
        self.kafka_client = None
        log.info("Connecting to kafka...")
        while (self.kafka_client is None): 
            try:
                self.kafka_client = pykafka.KafkaClient(hosts=self.kafka_hosts)
            except Exception, e: 
                t, v, tb = sys.exc_info()
                ntries +=1
                if (ntries > self.connect_retries) and (self.connect_retries != -1):
                    raise t, v, tb
                log.exception("Could not connect to kafka: %s. Retrying in 1 second. Try %d/%d.", str(e), ntries, self.connect_retries)
                sleep(1)

        log.info("Looking for a topic %s...", self.topic_name)
        while self.topic_name not in self.kafka_client.topics: 
            log.error("Could not find topic at the kafka brokers. Updating info and retrying in 1 second")
            sleep(1)
            self.kafka_client.update_cluster()
        self.topic = self.kafka_client.topics[self.topic_name]

        log.info("Creating a balanced consumer...")
        self.consumer  = self.topic.get_balanced_consumer(
               consumer_group=self.consumer_group, 
               zookeeper_connect=self.zoo_hosts, 
               consumer_timeout_ms=timeout_ms,
               auto_commit_enable=True)
```
Each consumed message in a test message set had unique id; and what i do with them then received, is inserting in a database. When I have this reconnection code, I got duplication primary key errors, meaning the consumer processed some messages twice (or more)

Could you please clarify if it is what is expected to happen? 

Note: if no reconnection is done during consumption, no duplication primary keys raised, confirming that the IDs of the test dataset are unique... 

Thanks

**Comment by yungchin** [comment]
@tigran-a kafka currently doesn't offer facilities that could really ensure "exactly once" delivery. There are some interesting notes here: https://cwiki.apache.org/confluence/display/KAFKA/Idempotent+Producer - your case is basically the second one, and as Jay Kreps writes, the way to deal with that would be to insert your offsets into the database together with the data, and to also load them from the database on starting a new consumer (as of #324, there's a callback interface for that on `BalancedConsumer`).

I suspect that what's happening in your example specifically, is that when you `stop()` your consumer, that leaves a brief amount of time for another `BalancedConsumer` in the same group to take control of those partitions, and when you then restart the first one, there's a small window where they consume concurrently and duplication may occur.

**Comment by tigran-a** [comment]
@yungchin thanks, but it's still not clear for me, as I have those sequential actions: 
1. The consumer (successfully) consumed a message (the next one is not yet consumed)
2. The consumer commits offset (so the last position should point to the next message)
3. The consumer is shut down
4. New consumer is created (and should use the last known position, which should point to the next message) 

However this does not happen. What am I missing? 
Doesn't the consumer.consume() send the ACK to the broker? 
Also, in my case I had one instance of that script, so at each moment of time only one balanced consumer is running.

Thanks

**Comment by emmett9001** [comment]
@tigran-a `consumer.consume()` actually [does not](https://github.com/Parsely/pykafka/blob/e3fb2e95ff29d9bfcb080991ad6dcbf140a71ac9/pykafka/simpleconsumer.py#L357) communicate with the server in any way. The consumer periodically runs `fetch()` on a worker thread that gets messages from the broker and populates an internal queue with those messages. `consume()` then consumes that queue one message at a time. This means that there is a difference between the messages you've seen from `consume()` and the messages that pykafka has actually fetched from the broker at the time that you reinstantiate the consumer. However, the offset committed to kafka is that of the last message returned from `consume()`, so I'm still unable to put my finger on a circumstance that enables the error you're seeing. 
One thing that strikes me when looking at your reconnect code is that you're allowing `self.consumer` to persist until the very end of the reconnect logic. The consumer instance holds a reference to the internal `Cluster` instance - I don't see any direct ways this could cause problems, but it's at least something I think you don't mean to be doing.
More broadly - I wonder what happens if you remove as much of your reconnect code as possible. There's a lot of state that gets destroyed locally, on zookeeper, and on the kafka broker when you stop the client once every second. Though I can't discern exactly what's happening, I bet you'll have better luck if you reconnect less frequently, or only in response to exceptions from the consumer. To my knowledge, all of the common errors in the consumer now result in exceptions being raised to the caller's thread, so you should have no problem simply waiting to reconnect when they're caught.
Please post here if you make any headway on this. Thanks!

**Comment by emmett9001** [comment]
@tigran-a I replicated your error with [this script](https://gist.github.com/emmett9001/2668d2c4a919ed89c8d2), which is as close as I could get it to your test code. I noticed the issue I fixed in #397, which is waiting for a second opinion from @yungchin. It would also be great if you could give that branch a try to see if it solves your use case.

**Comment by tigran-a** [comment]
@emmett9001 I've just made a test with 2.1.1 and with the current master. 
In the 2.1.1 I had the same issue with duplicating messages. However master branch worked fine. 

Thanks.

**Comment by tigran-a** [comment]
Hi, may I know when is the planned date for the release 2.1.2? Thanks

**Comment by emmett9001** [comment]
@tigran-a I'm planning to cut 2.1.2 in the next few days, certainly by the end of the week.
