### ISSUE TITLE
Put Changes.rst updates in tag

### ISSUE THREAD

**Issue by ottomata** [Parsely/pykafka#394]
Hiya!  This is just a pedantic request!  I've noticed that in the last two tags, the update to the CHANGES.rst for the changes in the tag arrived in a commit to master after the tag was made.  This confused me for 2.1.0, as I was only looking at the CHANGES.rst file for that tag, and wasn't sure what had made it in.

In the future, could you modify the CHANGES.rst file before that tag is made?  In my own projects, I've done this by updating the changelog in the commit that actually made a change.  E.g., you could maintain a 2.1.1 (SNAPSHOT) (or (ALPHA) or (WHATEVER)) tag at the top of CHANGES.rst, and then change it so it says the date of the tag when you make the tag.

Or do whatever you want! :)  Thank you!

**Comment by emmett9001** [comment]
@ottomata Thanks for the input. My method has been to tag the latest commit, then write and commit changes to the changelog and version number. Now that I think of it, my original reason for doing it this way doesn't make any sense - it doesn't actually keep the `/compare` view any cleaner since the changelog updates from the previous version leak in. I think i'll start including the changelog commit in future versions.

**Comment by ottomata** [comment]
Thanks! :)
