### ISSUE TITLE
Cannot wait until a certain message is delivered

### ISSUE THREAD

**Issue by magcius** [Parsely/pykafka#398]
Hi. I want to wait until a certain message is guaranteed to be delivered. Theoretically, I could do this by spinning `get_delivery_report` in a loop, and reading out the reports that come back. Since `produce` produces an internal `Message` which it doesn't return, I can't get anything to identify the resulting message. The best I can get is a binary compare on the `message` value, which could be incorrect if I send the same message multiple times.

If the producer returned the internal `Message` from `produce`, this would be OK. I could then wait until a certain message has been successfully delivered.

For now, I suppose I will call the private, internal `_wait_all` API.

**Comment by emmett9001** [comment]
@magcius Good point. This makes me realize that our `get_delivery_report` assumes that messages will be distinguishable from each other. An option now is to add some unique identifier to the message value before producing it. Returning the `Message` instance or some other identifier is something I can see being added in the future. Thanks!

**Comment by yungchin** [comment]
If you can afford dedicating a thread to it, a blocking call to
`get_delivery_report()` would work well for this: if you only produced one
message from the current thread, and then block on `get_delivery_report()`,
you're guaranteed to only get a report for that exact message. You're fine
using the producer from other threads concurrently - the delivery report
queue is thread-local.

And in that use mode, you're code would be even simpler if you set
`sync=True`, which would have all the delivery report checking get handled
internally in the `produce()` call.

(Also, note that the rdkafka-backed producer doesn't support the use of
`_wait_all()` for this, because it assumes it will only ever be called from
`stop()` and would otherwise block forever.)

**Comment by magcius** [comment]
We want to send a large number of messages to a topic, and then pause for a synchronization point before continuing. Doing synchronization on all of our messages would be too slow.

If `_wait_all` is not a supported API, why is it in the documentation?

http://pykafka.readthedocs.org/en/latest/api/producer.html#pykafka.producer.Producer._wait_all

**Comment by yungchin** [comment]
Aha, thanks - so if that's the use case, I'd actually suggest that you keep
count of the number of messages you produced, and then dequeue just as many
delivery requests. While that may not sound particularly elegant, it would
in fact be safer than matching the last message produced, because if you
have a nonzero `max_retries` your delivery reports could be out of order.
On the other hand, there's a hard guarantee that there shall be exactly 1
delivery report for each `produce()` (provided that did not raise an
exception directly). I should add that to the delivery-reporting docs.

We've been working with the convention that underscore-prefixed attributes
are considered private, and you're definitely right that that also deserves
a clear mention somewhere in the docs.

**Comment by yungchin** [comment]
> and then dequeue just as many delivery requests

s/delivery\ requests/delivery\ reports

**Comment by emmett9001** [comment]
Added a note about private interfaces [here](https://github.com/Parsely/pykafka/commit/4dcbf2ee841ef6e3cf8321f42da481ad30719dce).

Counting the produced messages and ensuring the same count of delivery reports sounds acceptable to me, so I think we can get away with simply being clearer about that in the docs. That said, is there any good reason that `produce` doesn't return the `Message` instance (other than the fact that we've kept the `Message` class private up to this point)? It seems like a very easy thing to add.

**Comment by emmett9001** [comment]
An update here (cc @magcius) - we've been discussing this change and while we all agree that it doesn't cause any new problems, it also doesn't truly solve the issue you're experiencing. This is mainly because of the possibility of out-of-order message production, which would make a naive comparison between the returned `Message` and the one from the delivery report fail. Additionally, returning a non-`None` value from a side-effecting method such as `produce` is not the most intuitive API design choice, and we would still like to reserve the possibility of further fleshing out the `Message` implementation before we make it so readily available via a public API.

Currently the best way to solve the original issue on this ticket is to count the number of produced messages and compare it to the number of delivery reports every so often. We will keep the pull request open and hopefully merge it in the future when the `Message` interface is a bit more well-developed.

**Comment by kariya2** [comment]
Any update on this? I can't afford to wait on delivery reports and the multi threaded blocking approach suggested by @yungchin is messing up the order of the messages which is very important for my application. any suggestions? 

I'm ok with spawning threads or passively listening for delivery reports separately, we just really need ordering to be correct.

**Comment by johnistan** [comment]
The only way to guarantee strong producing order is to use a sync producer with strong ack setting. Send message get an ack from kafka and then send another message. This is supported in the current client but will be significantly slower then the async api.

Also note this is not a limitation of this client implementation. Enforcing strong ordering between to machines is a hard problem and this limitation will be present in all kafka clients.
