### ISSUE TITLE
KeyError 7

### ISSUE THREAD

**Issue by saturnboy** [Parsely/pykafka#401]
I'd like some help understanding what to do in the case of a Kafka Error 7 - RequestTimedOut, especially while trying to commit offsets.  Using the latest pykafka 2.1.1 against Kafka 0.8.2, I occasionally see:

```
KeyError: 7
    ..my code calls..
    self._consumer.commit_offsets()
  File "pykafka/balancedconsumer.py", line 720, in commit_offsets
    return self._consumer.commit_offsets()
  File "pykafka/simpleconsumer.py", line 431, in commit_offsets
    partitions_by_id=self._partitions_by_id)
  File "pykafka/utils/error_handlers.py", line 50, in handle_partition_responses
    error_handlers[errcode](parts)
```
Since RequestTimedOut appears to be a valid response, not a `SocketDisconnectedError` or `IOError`, pykafka's internal error handling and retry logic is completely unused, and I get the error thrown all the way back to my code.

Is this intended?  Or is there some way to make pykafka handle this for me? Does anyone else see this error?

Especially in the case of committing offsets, it would be nice for pykafka to allow more error handling config...sometimes I want to ignore offset commit error, sometimes I just want to wait and retry, sometimes I want to die.

**Comment by yungchin** [comment]
@saturnboy thanks for reporting this - that's a bug. We should get a handler in place so that the normal retry logic will work.

Before 2.1.0 any KeyErrors in this function would be silently dropped, which is why nobody will have seen it until now.

As for configurability enhancements: do you want to open a separate issue to discuss that? Off the cuff, I suspect we could support the uses you describe by allowing `offsets_commit_max_retries=-1` to mean "infinite retries", and by always raising exceptions if max retries is ever exceeded, but I'd have to have another look to figure out if that's a backwards-compatible change.

**Comment by emmett9001** [comment]
Thanks @saturnboy, I've opened PR #404 to handle this case. If you'd like to test it out, please feel free.

@yungchin, I do think error handling config is something we can consider adding - we can have a separate ticket for that if you'd like. I'm not sure what it would look like, so it does warrant some discussion.

**Comment by saturnboy** [comment]
@emmett9001 @yungchin For all of my current and future needs, I think -1 for infinite retry, plus raise on max retry exceed (as it already does) is sufficient.
