### ISSUE TITLE
slow to connect via zookeeper

### ISSUE THREAD

**Issue by matthewatabet** [Parsely/pykafka#430]
Hi there,

According to this logic:
https://github.com/Parsely/pykafka/blob/1b2d030b073f276c18fd6b1a64320de58d4d7904/pykafka/cluster.py#L240

It seems that PyKafka first attempts to connect to each seed host as if it were a Kafka node. Then, if this fails, it attempts to connect using the Zookeeper protocol. This means that connecting through ZK can take much longer than connecting directly to the Kafka nodes.

Here's the producer I'm using:

```python
#!/usr/bin/env python
import logging
import time

from pykafka import KafkaClient


def main():
    s = time.time()
    client = KafkaClient(hosts='127.0.0.1:2181')
    topic = client.topics['my_channel']

    with topic.get_sync_producer(required_acks=0,
                                 linger_ms=0,
                                 min_queued_messages=1) as producer:
        for i in range(0, 1):
            producer.produce('test message')
    print time.time() - s

if __name__ == '__main__':
    main()
```

When testing, the only difference is whether `hosts` is a set of Kafka nodes or a set of ZooKeeper nodes. In the ZooKeeper case, sending a single message requires about 6s including connection time. In the Kafka case, it takes 100 milliseconds. In my use case, I need to simply send a single message as quickly as possible.

Am I doing anything incorrectly here?

It might be nice if the `KafkaClient` had an explicit `zookeeper_hosts` argument. That way, the client wouldn't have to first try the Kafka connection.

Thanks a bunch!

**Comment by emmett9001** [comment]
@matthewatabet You're not doing anything wrong. You're correct that initial setup does take longer if you're using a ZooKeeper connection string, since you have to wait for several timeout iterations on the kafka host attempts. There currently isn't any good way around this, since altering `socket_timeout_ms` will adversely affect the rest of the operation of the `KafkaClient`. I initially wanted to avoid complicating the `KafkaClient` interface by adding another keyword argument for zookeeper hosts, but this is a reason we might want to reevaluate that decision.
