### ISSUE TITLE
Provide CFFI bindings for rdkafka or a Pure Python version for PyPy

### ISSUE THREAD

**Issue by thedrow** [Parsely/pykafka#439]
cpyext is much slower on PyPy. We need to provide CFFI bindings for librdkafka in order to match the throughput of the CPython extension.
Alternatively we can provide a pure python version and disallow building the extension under PyPy.
This is a question of throughput and when the GIL can be released.
Will C always be faster than PyPy in this case? Are there opportunities to release the GIL before I/O occurs?

**Comment by yungchin** [comment]
Thanks for bringing this up, it was a choice I haven't really documented before. We actually started off with a set of CFFI bindings for librdkafka (the basis of which you can still find at https://bitbucket.org/yungchin/python-librdkafka/src - but I should add a note there that it's abandoned code). The problem with those was that in practice, it turned out that some calls into libffi were so expensive, that the pure pykafka code ran faster than the rdkafka-backed code.

In the profiling I did, I found that while the actual `consume()` calls were very fast, getting the payload out of the resulting `cdata` via a `cast()` (see [here][1] and [here][2]) turned out prohibitively slow. Note this was for CFFI on CPython - at the time we hadn't done any work towards pypy support yet - but I suspect the problem isn't any different on PyPy: the bottleneck seemed to be the handling of pointer dereferencing via libffi calls, which should work the same with both interpreters.

> Alternatively we can provide a pure python version and disallow building the extension under PyPy.

At build-time, we can't see if the intention is to use pypy at run-time. But certainly, using the C extension is currently not safe with pypy (I've noted this in the readme) and I'd recommend against it. The producer e.g. assumes that PyObject references are stable void pointers, which is not guaranteed on pypy.

Thanks

[1]: https://bitbucket.org/yungchin/python-librdkafka/src/8cf3c91bebfee4b3640735215ba85f22b08c73ec/rd_kafka/message.py?at=master&fileviewer=file-view-default#message.py-21
[2]: https://bitbucket.org/yungchin/python-librdkafka/src/8cf3c91bebfee4b3640735215ba85f22b08c73ec/rd_kafka/utils.py?at=master&fileviewer=file-view-default#utils.py-20

**Comment by thedrow** [comment]
When you execute the setup.py you can check if the platform you're running on is PyPy and then exclude the extension from the installation.
See https://github.com/getlogbook/logbook/blob/master/setup.py#L210 for example.

**Comment by thedrow** [comment]
@yungchin Have you filed a bug report to PyPy? They consider performance issues as bugs and I'm sure they would love to hear about this case.
You might have uncovered a bug in CFFI.
