### ISSUE TITLE
Produced messages getting lost when broker is down

### ISSUE THREAD

**Issue by jonsource** [Parsely/pykafka#457]
Hello, I have the following issue with pykafka, in this setting:

Running 3 kafka brokers and 1 zookeeper in docker on one machine in docker
zookeeper 172.17.0.2:2181
kafka[1-3] 172.17.0.[3-5]:9092
all default configs except kafka `config/server.properties` has 
`leader.imbalance.check.interval.seconds = 30` added, otherwise the topic leader rebalancing interval is too long - 5 minutes.
_(actually I noticed first in a real high availability cluster with 3 kafka brokers and 3 zookeepers, but that's not important I think - I reduced the problem into a local setting)_
using pykafka latest commit 0891c81 or 2.2.0, python 2.7.6, kafka 0.9.0.0, zookeeper 3.4.6, docker 1.9.1, running on Ubuntu 14.04

I send a few messages to be produced, then stop one of the kafka containers (simulating a failure) and send a few more - _(source added in gist)_. Messages for the broker that has stopped get lost.

The strange thing is pykafka reconnects all-right after a few time-outs, starts the proper worker threads, but doesn't send the messages. But during the time-out pykafka attempts to resend the messages, it seems it forgets them when the reconnect occurs _(logfile in the gist)_.
I reduced the problem to a gist here: https://gist.github.com/jonsource/4f5ec5b345f75f21b16b
with a log of a typical run, and testPykafka.py source at the bottom.

One more strange thing I noticed - the messages get lost when pausing kafka1 or kafka2. When kafka3 is paused, they get sent OK after the reconnect.

Best regards.

**Comment by emmett9001** [comment]
Thanks @jonsource. I'll have to dig into this one, but at a glance it does look like a real bug.

**Comment by cscheffler** [comment]
I have found similar behaviour using pykafka 2.2.0, but even when there is not a full Kafka broker failure. (Not tested using the latest master branch, so not sure whether this has been resolved there. I'll try to confirm today.)

Particularly, using

 * a 3-broker Kafka cluster,
 * a topic with 120 partitions and replication factor 2.

Start a pykafka producer that sends a message containing a counter (i.e. first message is "0", second is "1", etc.) at a rate of about 100 per second.

While the producer is running:

 * Stop kafka broker 1 – leader changes on 40 partitions, pykafka notices and after a while starts producing to the new leader.
 * Start kafka broker 1 – nothing changes
 * Stop kafka broker 2 – leader changes, pykafka notices and after a while starts producing to the new leader.
 * Start broker 2.
 * Stop and start broker 3.

Stop the producer.

Look at the messages on the topic. A handful of them are missing.

Just wanted to log this here for now. I'll see if I can provide more specific information a bit later.

**Comment by cscheffler** [comment]
Update:

The test report above was using pykafka 2.2.0.

Using the latest commit on the master branch (3924b9f4503b4c13bddec09782b517fc05c62adf), everything seems to work just fine when doing a rolling restart of Kafka brokers and we are producing to and consuming from a replicated topic. 2.2.0 loses messages fairly consistently.

Going to do a aggressive test next: multiple simultaneous broker failure.

**Comment by cscheffler** [comment]
Hmmmm... I take that back. It still loses messages sometimes – just less frequently.

**Comment by cscheffler** [comment]
Whenever a consumer or a producer falls over, this messages seems to come up in the logs:

For (simple) consumer:

    Unhandled exception in thread started by <__main__.ConsumerThread instance at 0x10d6ff170>
    Traceback (most recent call last):
      File "tal_kafka/scripts/test_pykafka_stability.py", line 106, in __call__
        message = consumer.consume()
      File "/Users/carl/code/pykafka/pykafka/simpleconsumer.py", line 381, in consume
        self._raise_worker_exceptions()
      File "/Users/carl/code/pykafka/pykafka/simpleconsumer.py", line 205, in _raise_worker_exceptions
        raise ex
    RuntimeError: Unable to connect to a broker to fetch metadata. See logs.

For producer:

    Unhandled exception in thread started by <__main__.ProducerThread instance at 0x10f734b00>
    Traceback (most recent call last):
      File "tal_kafka/scripts/test_pykafka_stability.py", line 92, in __call__
        producer.produce(message_prefix + '%06i' % self.count)
      File "/Users/carl/code/pykafka/pykafka/producer.py", line 183, in __exit__
        self.stop()
      File "/Users/carl/code/pykafka/pykafka/producer.py", line 233, in stop
        self._wait_all()
      File "/Users/carl/code/pykafka/pykafka/producer.py", line 399, in _wait_all
        self._raise_worker_exceptions()
      File "/Users/carl/code/pykafka/pykafka/producer.py", line 168, in _raise_worker_exceptions
        raise ex
    RuntimeError: Unable to connect to a broker to fetch metadata. See logs.

**Comment by emmett9001** [comment]
@jonsource Have you tried increasing the producer's `max_retries` setting? One thing I notice about your log output is that the retry happens exactly three times, which is the default setting for `max_retries`. I think it's possible that you're waiting longer than it takes three retries to happen before you restart the broker, at which point the messages are no longer retried.

**Comment by emmett9001** [comment]
@cscheffler That traceback you posted is expected, and it doesn't [necessarily](https://github.com/Parsely/pykafka/blob/5c90e16271963630dcb6d9226b942f0a129b33ab/pykafka/cluster.py#L241) indicate a crash. I recommend adjusting `max_retries` on the producer and seeing if that changes anything. Can you make `max_retries` high enough that you don't lose any messages?

**Comment by cscheffler** [comment]
@emmett9001 No, adjusting `max_retries` doesn't help. I think you are looking at the wrong exception. [This](https://github.com/Parsely/pykafka/blob/5c90e16271963630dcb6d9226b942f0a129b33ab/pykafka/cluster.py#L274) is the one I'm getting.

I increased `max_retries` to 100 on the producer and ran the test again, but it still fails.

Here is my test code and  log output:

* [Test script](https://gist.github.com/cscheffler/ca334adc5427956e0745#file-test_pykafka_stability-py) (just for reference – it requires vagrant environments set up, so you won't be able to run it).
* [Console output](https://gist.github.com/cscheffler/ca334adc5427956e0745#file-console_output-txt) from the test script (the crash is around line 50).
* [Full log output](https://gist.github.com/cscheffler/ca334adc5427956e0745#file-test_pykafka_stability-log) (level = INFO).

From the console output, you can see that the producer and consumer do both crash, since the count of messages produced and consumed gets stuck (stops increasing) after the crashes.

I'll see if I can figure out why this happens. It really shouldn't since there are at least 2 out of 3 brokers alive at any time during the test.

**Comment by jonsource** [comment]
@emmett9001 Increasing max_retries to 5 seems to solve my problem - but what is strange: with max_retries=3 messages get consistently lost when kafka1 or kafka2 are paused, but all messages are successfully delivered when kafka3 is paused - this led me astray while looking for the problem.

I added some more debug messages to pykafka and generated new logs here: https://gist.github.com/jonsource/2209f4835e261cfe95d7

**Comment by jonsource** [comment]
@cscheffler kafka by default takes 5 minutes! to re-elect new leaders when a partition leader goes missing, it might not be enough to increase the max retries to 1000 without modifiing the kafka cluster settings - `leader.imbalance.check.interval.seconds`. I use `leader.imbalance.check.interval.seconds=30`.

**Comment by cscheffler** [comment]
Ok, I managed to resolve all my problems (sort of) by tweaking Kafka (and not fixing anything in pykafka).

1. [Make sure your Kafka brokers shut down gracefully](http://kafka.apache.org/documentation.html#basic_ops_restarting)
2. Be more conservative with your `required_acks` parameter. This makes sure that no messages get lost by waiting for all Kafka brokers to acknowledge a produce request.

Number 2 has the drawback that you will get duplicate messages on your topic, since during a Kafka broker restart the producer will think that some produce requests failed (`acks` < `required_acks`). This does however match Kafka's at least once delivery philosophy.

With `required_acks` set to 1 (the default), you will regularly lose produced messages (even if your topic has replication factor > 1) when a kafka broker is restarted. However, in that case I have never observed duplicate messages.

Thanks for all the advice.

**Comment by emmett9001** [comment]
Thanks for the information, @cscheffler - It's really helpful to have this practical information written down.

**Comment by jonsource** [comment]
Sorry to bother you again - after tuning up my kafka cluster the leader changes, when a broker goes down or is restored up, happen in less than 10 seconds. But I still encounter two kinds of problems connected to the same scenario.

1) When a broker goes down, and I call producer.stop() before all messages are sent, the main thread stops early and won't wait for the retries to happen. I can hard-code the main thread to wait for some time, but it doesn't feel right. Maybe I'm missing something important. Gist with script to recreate the error on a dockerised 3 kafka cluster and logs: https://gist.github.com/jonsource/b82f1a3bac3e5c83aa4f

2) When use_rdkafka=True on my producer, messages are getting lost after a broker goes down. Even when retrying far longer then it takes for the leader re-election (which I can check in a separate process). Gist with script and logs: https://gist.github.com/jonsource/5b1d7ce83d49674a44c6

3) Also the behaviour of retry_backoff_ms varies greatly between using rdkafka and not. While using rdkafka it equals the time spent between attempting a new re-send, but when not using rdkafka - the time it takes to resend previously failed messages seems to depend also on linger_time_ms and possibly socket_timeout_ms and the internal timeout `time.sleep(i)` in `Broker.request_metadata()` on `broker.py:280`

Thank you for your support.

**Comment by emmett9001** [comment]
@jonsource do you mind opening separate issues for 2 and 3? That will make sure they don't get lost in the shuffle.
