### ISSUE TITLE
rdKafka not able to resend messages to other brokers after one goes down

### ISSUE THREAD

**Issue by jonsource** [Parsely/pykafka#466]
When use_rdkafka=True on my producer, messages are getting lost after a broker goes down. Even when retrying far longer then it takes for the leader re-election (which I can check in a separate process) and not due to message time-out. The messages are not resent even after the broker reconnects.

Gist with script and logs: https://gist.github.com/jonsource/5b1d7ce83d49674a44c6

**PyKafka version**: 2.2.0, latest (c3a4b5b)
**Kafka version**:0.9.0.0

**Comment by emmett9001** [comment]
@jonsource I apologize that this issue fell through the cracks a bit. It's certainly worth digging into, maybe @yungchin can provide some additional information.

**Comment by yungchin** [comment]
@jonsource apologies for missing this earlier.

How many partition replicas did you have on kafka, for this test? And what version of librdkafka did you build against? I'm wondering if this fix might be related: https://github.com/edenhill/librdkafka/commit/b38b38b02a2c7a287bc2c949a11225b255d92028 - it would affect a scenario where you have no available replicas. Could you retry with a newer librdkafka build?

Something else that somewhat puzzles me is that in your logs, our rdkafka polling thread seems to exit, when there are apparently still some requests outstanding: https://gist.github.com/jonsource/5b1d7ce83d49674a44c6#file-rdkafkaoff-log-L405-L411
This shouldn't ever happen because the polling thread keeps going until the out-queue is empty:
https://github.com/Parsely/pykafka/blob/3dba44438070ad9addca5089591620c658ba8060/pykafka/rdkafka/producer.py#L59
.... but if it did happen, for some reason that I'm missing, it might explain why the producer fails to stop and the program gets stuck.

**Comment by emmett9001** [comment]
I'm going to close this since it sounds like there's a reasonable chance it's not directly related to pykafka itself, and we don't have any additional information that would help us debug. @jonsource if you have additional information to provide, please comment here and we might have a better chance of getting this one fixed.
