### ISSUE TITLE
Producer Batch Size Param

### ISSUE THREAD

**Issue by jofusa** [Parsely/pykafka#482]
This is another thought when thinking about the compression max message size issue in #480.

Right now the producer empties the entire queue when producing messages. It i think this should be a configuration variable: `producer_batch_size`.

Is my reading of the code correct?

https://github.com/Parsely/pykafka/blob/master/pykafka/producer.py#L543

**Comment by emmett9001** [comment]
@jofusa Looks like your reading of this code is correct. The official producer does support a `batch.size` configuration variable, so I think it makes sense to support it here as well.

That said, it is already possible to affect the size of batches with the `min_queued_messages` kwarg on `Producer`. Maybe you can verify whether or not adjustments to that argument can fix your use case?

**Comment by jofusa** [comment]
ah thanks for the clarification, just saw that param as well. I will adjust this. The newer version of the java client now batches on message size. I state this from kafka user group email:

> Hello,
> 
> Did you have compression turned on and batching (in terms of #.messages)?
> In that case the whole compressed message set is treated as a single
> message on the broker and hence could possibly exceed the limit.
> 
> In newer versions we have changed the batching criterion from #.messages to
> bytes, which is aimed at resolving such issues.
> 
> Guozhang

I have yet to find the actual commit, but the idea of setting a max message size that is controlled by the client still strikes me as a good idea.

**Comment by jofusa** [comment]
from the kafka 0.9.0 docs:

```max.request.size	The maximum size of a request. This is also effectively a cap on the maximum record size. Note that the server has its own cap on record size which may be different from this. This setting will limit the number of record batches the producer will send in a single request to avoid sending huge requests.	int	1048576```

**Comment by emmett9001** [comment]
My main worry is that batch sizing code could stand to complicate the producer significantly. If there is a way to make it work by adjusting `min_queued_messages`, I'd strongly prefer to recommend that solution to users rather than add more keyword arguments. If there really is a problem that can only be solved by adding this argument, that's a different situation. However, it's not yet clear to me that that's the case.

Note that there are a lot of configurations supported by the official JVM consumer and producer that pykafka doesn't support due to differences in its internal design. We've never been worried about strict configuration parity with these tools. Our primary concern is that the API remains pythonic and easy to use.

**Comment by jofusa** [comment]
agreed on all points. mirroring the java api directly is not advisable. (but looking to how they deal with similar problems is a good idea)

`min_queued_messages` is exactly what i was looking for. I would only suggest a doc change to call attention that is param can be used to control producer batch size

**Comment by jofusa** [comment]
pr in. 

I had a separate thought about the sync producer. Shouldn't the `min_queued_messages` always be `1` for a sync producer?

**Comment by emmett9001** [comment]
@jofusa You're right, a producer with `sync=True` should always have `min_queued_messages=1`
