### ISSUE TITLE
Identical KafkaClient is created in different process

### ISSUE THREAD

**Issue by lucidfrontier45** [Parsely/pykafka#490]
Hi all. I'm working on Simple Task worker that contains a Kafka consumer.
My code is as follows.

```python
from multiprocessing import Process

from pykafka import KafkaClient


class KafkaWorker(Process):
    def __init__(self):
        Process.__init__(self)

    def run(self):
        print("{} start".format(self.pid))

        c = KafkaClient(hosts="127.0.0.1:9091")
        print("{}'s client id = {}".format(self.pid, id(c)))
        topic = c.topics["test"]
        consumer = topic.get_balanced_consumer(consumer_group='testgroup',
                                               auto_commit_enable=True,
                                               zookeeper_connect="127.0.0.1:2281")
        for msg in consumer:
            print(self.pid, msg.value)


w1 = KafkaWorker()
w1.start()
w2 = KafkaWorker()
w2.start()
```
When I run this code, it says

```python
13452 start
13453 start
13452's client id = 139805036298320
13453's client id = 139805036298320
No handlers could be found for logger "pykafka.balancedconsumer"
Process KafkaWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/du/PycharmProjects/BusyBee/examples/kafka_test.py", line 19, in run
    for msg in consumer:
  File "/home/du/.virtualenvs/busybee/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 722, in __iter__
    message = self.consume(block=True)
  File "/home/du/.virtualenvs/busybee/local/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 711, in consume
    raise ConsumerStoppedException
ConsumerStoppedException
```
You can see the two KafkaClient instances have the same id and one of the consumers gives `ConsumerStoppedException`.

What is the right way to include KafkaClient in a Process?  

**Python version**: 2.7
**PyKafka version**: 2.2.1
**Kafka version**: 0.9.0.1"

**Comment by emmett9001** [comment]
Hi @lucidfrontier45. The first thing I notice about your example code is that the `KafkaClient` `id`s being the same may not be meaningful. Consider the simple example

```python
from multiprocessing import Process

class Worker(Process):
    def run(self):
        a = []
        print(id(a))

w1 = Worker()
w1.start()
w2 = Worker()
w2.start()
```

If you run this, you'll see that both processes print the same id for the list object. I believe this happens because python object IDs are only guaranteed to be unique per process - the fact that they share an ID doesn't actually indicate that they're the same object.

Additionally, after producing some messages to the `test` topic and ensuring that your example script points correctly to my local kafka and zookeeper instances, I'm actually able to consume messages properly in both processes without hitting a `ConsumerStoppedException`. I did see the exception before I had corrected the zookeeper and kafka cluster hosts in the script, but it went away once I'd done that.

Are you certain that your script is pointing to the correct zookeeper and kafka hosts, and that those hosts are accessible from the machine you're running this script on?

**Comment by lucidfrontier45** [comment]
Hi @emmett9001 . Thank you for respond.
After restarting my kafka cluster, now I got this error

```python
KafkaException("Cannot add consumer: more consumers than partitions")
```
I increased the number of partitions and my code started to work!

Thank you for advice.
