### ISSUE TITLE
Kafka consumer partition offset off by 2?

### ISSUE THREAD

**Issue by zhaojack** [Parsely/pykafka#494]
Hi,

I have a kafka topic with a single partition. I would like to create a consumer with the single purpose of returning me the last message that was produced on the channel (and that's it).

The use case is that this is run by the producer at the beginning of each run. The producer listens to some other data source and relays any new entries into the kafka topic. In the case of producer downtime or failures, it needs to recover from where it last left off.

Please let me know if any of the below are not the correct ways to do this. This is basically what I have:

    def getKafkaTopic(topic):
        client = KafkaClient(zookeeper_hosts=getZookeeperHosts())
        return client.topics[topic]

and then

    topic = getKafkaTopic('some.topic.name')
    consumer = topic.get_simple_consumer(consumer_group="some_consumer_group")
    partitions = [p for p in consumer.partitions.itervalues()]
    offset_pairs = [(p, p.latest_available_offset() - 2) for p in partitions]
    consumer.reset_offsets(partition_offsets=offset_pairs)

This works. However, I'm baffled at the requirement for `p.latest_available_offset() - 2`.

Given that an offset value in kafka points to the "next message to be consumed", I would expect a consumer at `p.latest_available_offset()` to block until the next message is produced, so that would be as expected. However, `p.latest_available_offset() - 1` will also block until the next message is produced, whereas `p.latest_available_offset() - 2` will get me the last message produced.

Is this an off by one error somewhere in pykafka? Or am I just not understanding kafka?

Thanks,
Jack

**PyKafka version**: 2.2.0
**Kafka version**: 0.8.2

**Comment by emmett9001** [comment]
Hi @zhaojack, thanks for filing this. The behavior you're seeing is a consequence of pykafka's handling of the "funky" Offset API. The Offset API accepts timestamps, not offset values. To allow users to reset to specific offsets, pykafka attempts to treat them as timestamps and assumes they're offset values as a fallback.

Effectively, the offset value you give in `reset_offsets` is treated as the offset most recently consumed by the consumer. If you pass `latest_available_offset - 1`, the consumer understands this to mean that `latest_available_offset - 1` was the last offset consumed, and that `latest_available_offset - 1 + 1` should be the next message consumed. Since `latest_available_offset` doesn't exist on the topic yet (due to the way that the Offset API works), the consumer hangs until it becomes available. If you pass `latest_available_offset - 2` to `reset_offsets`, the consumer sets its "next message" to `latest_available_offset - 2 + 1`, which is the actual latest message appended to the topic.

The [documentation](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetAPI(AKAListOffset)) of the Offset API indicates that

> The response contains ... the "log end offset" i.e. the offset of the next message that would be appended to the given partition. We agree that this API is slightly funky.

For this reason, I realize that `latest_available_offset` is a misleading name. The function should probably return an offset one less what it currently returns.

See [the logic you're hitting](https://github.com/Parsely/pykafka/blob/59c94b521056a02ae901d284d0da00aa75b68f9b/pykafka/simpleconsumer.py#L572-L592) in this example for more detail.
