### ISSUE TITLE
Producer deadlocks using `block_on_queue_full=True` with connection loss

### ISSUE THREAD

**Issue by andrewkcarter** [Parsely/pykafka#495]
**PyKafka version**: 2.2.1
**Kafka version**: 0.9.0.0

If the brokers become unreachable, the producer fails to send the batch. Upon failure, the producer attempts to enqueue the messages again, but if the queue is full and the `block_on_queue_full` producer property is set `True`, then the producer thread becomes deadlocked. Restoring access to the broker doesn't resume the producer.

Steps to reproduce:
1. Run sample given below
2. Set a breakpoint on this line: https://github.com/Parsely/pykafka/blob/26b62cd2094914298be8ecf8179c347be807e7d7/pykafka/producer.py#L439
3. Stop the broker
4. Step into the producer until it ultimately deadlocks on this line: https://github.com/Parsely/pykafka/blob/26b62cd2094914298be8ecf8179c347be807e7d7/pykafka/producer.py#L523

```
import time
from pykafka import KafkaClient

client = KafkaClient(hosts='localhost:9092')
topic = client.topics['ether']

producer = topic.get_producer(**{'max_queued_messages': 10,
                      'min_queued_messages': 5,
                      'linger_ms': 500,
                      'block_on_queue_full': True})

for i in range(0, 100000):
    print str(i)
    producer.produce(str(i))
    time.sleep(0.1)

producer.clean_up()
```

Also, I noticed `cluster.update()` retries `_max_retries` but doesn't have a back-off implemented, which might be an issue of it's own.

**Comment by emmett9001** [comment]
Hi @andrewkcarter, thanks for the detailed report. Do you mind updating your code links to be permalinks? Master has changed since you made them and it's not totally clear which lines you're linking to.

I'm not surprised this deadlock is possible. It will take a bit of digging, but I'm guessing it has a straightforward solution.

**Comment by andrewkcarter** [comment]
Updated links.

**Comment by emmett9001** [comment]
I dug into this a bit. Here's my current understanding of the sequence of events that causes this deadlock:

* Production is happening normally
* All brokers go down
* `_send_request`'s `_update` call on `SocketDisconnectedError` eventually fails because brokers are down
* `_send_request` calls `_produce` for retry
* Meanwhile, `produce()` calls from the main thread fill the queue and unset `slot_available`
* The retry `_produce` call results in a wait on `slot_available` in `enqueue`
* Since the worker thread and the main thread are both blocking on `slot_available`, there's a deadlock

This could maybe be solved with a new parameter on `enqueue` that causes `block_on_queue_full` to be ignored during retries.

**Comment by emmett9001** [comment]
The producer code around reconnects has changed enough since this was filed that it probably deserves another look.

**Comment by emmett9001** [comment]
Can't reproduce on current master, probably as a result of https://github.com/Parsely/pykafka/commit/b5be2527f2ea1392523003117a22de470ca562c7
