### ISSUE TITLE
Create a topic using pykafka 

### ISSUE THREAD

**Issue by asa88** [Parsely/pykafka#514]
I was wondering how can I create a new topic specifying the number of partitions using pykafka.  Essentially doing step 3 at https://kafka.apache.org/08/quickstart.html using pykafka. I found some code that is doing so in test https://github.com/Parsely/pykafka/blob/6035a91e5de93c9ffaec9c6b46844d6c4dba74b9/pykafka/test/kafka_instance.py but I am not sure how can I use it. 

Take a look at the following code:

```
from pykafka import KafkaClient
import ConfigParser
import os

'''Location of the Project '''
Project_loc= os.path.dirname(os.path.dirname(os.path.realpath(__file__)))


Config = ConfigParser.ConfigParser()
Config.read(Project_loc + '/Configs/database_custom' +'_config.ini')
client= KafkaClient(Config.get('Kafka_Server','host_name'))  # kafka server hostname and port

topic = client.topics['*Name of the Topic*']
print topic._partitions
balanced_consumer = topic.get_balanced_consumer(
     consumer_group='custom_test',
     auto_commit_enable=True,
     zookeeper_connect= ''Host:Port of zookeeper"
)

for message in balanced_consumer:
   if message is not None:
       print message.offset, message.value

```
The first time  I run it it starts up fine, however when I try to create a second instance it fails with the following error:

```
{0: <pykafka.partition.Partition at 0x103c23910 (id=0)>}
No handlers could be found for logger "pykafka.balancedconsumer"
Traceback (most recent call last):
  File "/Users/aarya/Work/Repos/dataframeanalytics/KafkaDataframe/src/Kafka-client_alt.py", line 23, in <module>
    for message in balanced_consumer:
  File "/Users/aarya/anaconda/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 746, in __iter__
    message = self.consume(block=True)
  File "/Users/aarya/anaconda/lib/python2.7/site-packages/pykafka/balancedconsumer.py", line 735, in consume
    raise ConsumerStoppedException
pykafka.exceptions.ConsumerStoppedException
```
What I noticed is that the number of partitions specified on the topic are zero, which brought me to the question in the heading. Let me know if there are any more clarifications I can provide.

**Comment by emmett9001** [comment]
HI @asa88, thanks for asking. Looks like you're using [this logic](https://github.com/Parsely/pykafka/blob/f001ccbf37b55248abcd00732f2f296884821081/pykafka/cluster.py#L94) to have Kafka autocreate a topic with a single partition for you. It actually doesn't [look like](http://kafka.apache.org/documentation.html#topic-config) Kafka currently supports configuring the default number of partitions on autocreated topics. In fact, the way topics are created [in the tests](https://github.com/Parsely/pykafka/blob/6035a91e5de93c9ffaec9c6b46844d6c4dba74b9/pykafka/test/kafka_instance.py#L93-L96) is to shell out to the Kafka command line tool.

PyKafka currently doesn't have its own way to create topics - in fact, since there's no API for doing so, the only way PyKafka *could* even do it at the moment would be this method of shelling out to the Kafka CLI. I recommend either simply sticking with the Kafka CLI-based method or pull requesting an addition of a Python wrapper for that tool into `cli/kafka_tools.py`.
