### ISSUE TITLE
BalancedConsumer consumer_group bytes requirement

### ISSUE THREAD

**Issue by rmfitzpatrick** [Parsely/pykafka#545]
Would someone be able to explain the bytes requirement to me?  When monitoring zookeeper consumers in a polyglot environment, I see that pykafka consumers all show as rendered byte strings ```b'consumer_group'``` when all other consumers are utf-8.

Doesn't it seem odd to be using partial byte strings in zookeeper paths?

**Comment by emmett9001** [comment]
Hi @rmfitzpatrick. The short answer is that we haven't done anything about better string support since the initial push to support python 3. I believe the reason for this requirement at the moment is that the consumer group string can be used in contexts where a bytestring is required, especially the protocol implementation. Since Kafka itself only accepts ascii strings as consumer group names, we wanted to avoid doing any magical transformations on passed unicode strings to make them fit. I do think this should be updated, though. You can see progress and discussion on more complete unicode support in pykafka in #405.
