### ISSUE TITLE
Balanced consumer does not show up in KafkaManager

### ISSUE THREAD

**Issue by asa88** [Parsely/pykafka#551]
I cannot see any pykafka consumer listed in KafkaManager 1.3 (https://github.com/yahoo/kafka-manager). I know it works as consumers from java, nodejs, and kafka-python client show up. Any insights on what may be happening or setting I need to enable would be helpful.

**Comment by emmett9001** [comment]
@asa88 Thanks for bringing this to our attention. I actually think this issue is more appropriate for the kafka-manager issue tracker than the pykafka one. It's possible that a pykafka `SimpleConsumer` might not show up in monitoring software since it doesn't register itself in ZooKeeper or Kafka like the `BalancedConsumer` classes do. If you find that there's an actual issue with pykafka that's causing this bug, please comment here.
