### ISSUE TITLE
Reset offset for unowned partitions in balanced consumer group

### ISSUE THREAD

**Issue by ketralnis** [Parsely/pykafka#557]
I want to be able to make all consumers in a consumer group go "back in time". That is, I have a balanced consumer group that has been running for a while, but I need it to reprocess some range of messages that are present in Kafka as if it hadn't seen them before. (note: this is _not_ the same as auto_reset, where you're creating the offsets for the first time if they aren't present.)

The obvious way to do this is:

```
    # find the partitions that we need to reset
    topic = kafka.topics[topic_name]
    partitions = topic.partitions.values()

    # build a consumer to get access to the consumer group API
    consumer = topic.get_balanced_consumer(consumer_group="consumer_group_name")

    consumer.reset_offsets(
        [(partition, epoch_timestamp*1000)
         for partition in partitions])
```

However, this throws an exception:

```
  File "/usr/lib/python2.7/dist-packages/pykafka/balancedconsumer.py", line 671, in reset_offsets
    self._consumer.reset_offsets(partition_offsets=partition_offsets)
  File "/usr/lib/python2.7/dist-packages/pykafka/simpleconsumer.py", line 593, in reset_offsets
    raise KafkaException("Unknown partition supplied to reset_offsets\n%s", e)
pykafka.exceptions.KafkaException: ('Unknown partition supplied to reset_offsets\n%s', KeyError(<pykafka.partition.Partition at 0x7f196afc55d0 (id=0)>,))
```

That's because SimpleConsumer is trying to ["turn Partitions into their corresponding OwnedPartitions"](https://github.com/Parsely/pykafka/blob/e18bdeb3586fab21493b755d564d6b4aa8ec7ef2/pykafka/simpleconsumer.py#L627). But I want to reset the stored offset in Zookeeper for Partitions that I don't own and that other consumers may currently be processing.

It may be okay for me to just take ownership of all of the partitions, reset the offsets, and then relinquish ownership so the other consumers in the group resume from wherever I reset them to. But I don't see a straight forward way to do that in pykafka's API.

**PyKafka version**: 2.1.2
**Kafka version**: 0.8.2

**Comment by emmett9001** [comment]
Thanks for filing this, @ketralnis. I see what you're trying to do, and I agree it may be appropriate in some situations. `reset_offsets` doesn't actually touch ZooKeeper directly, it only issues an `OffsetRequest` and resets PyKafka's internal offset counters for the specified partitions. In cases where you're resetting internal offsets for partitions owned by the consumer you're operating on and you're using `auto_commit_enable=True`, this does result in an update to ZooKeeper's held offsets when the automatic commit occurs. This is because a PyKafka consumer doesn't actually have any way to affect the ZooKeeper offsets for partitions it doesn't own.

I can see potentially adding a `partition_offsets` argument to `commit_offsets` so that [this logic](https://github.com/Parsely/pykafka/blob/e18bdeb3586fab21493b755d564d6b4aa8ec7ef2/pykafka/simpleconsumer.py#L453-L463) would not have to be limited only to `self._partitions`. I can't come up with anything that this would break off the top of my head, so if it's a pull request you'd like to pursue, I think it's reasonable. That said, this operation sounds like something I'd personally sooner look directly to ZooKeeper/kazoo for than PyKafka.

**Comment by ketralnis** [comment]
> I can see potentially adding a partition_offsets argument to commit_offsets so that this logic would not have to be limited only to self._partitions

If I'm understanding correctly, I don't think this would work. The other running consumers wouldn't know that you've done this and would just keep consuming at their current offsets. When they commit they'd overwrite whatever new offset you'd written out for them. Thinking on it this way, I think that forcibly taking ownership of all of the partitions is the only real way to reset their offsets without having your work just be undone again.

One saving grace is that this doesn't have to be atomic (for my purposes anyway) but looking at the [consumer rebalance algorithm](https://kafka.apache.org/documentation.html#impl_consumerrebalance) it doesn't look like "insisting" on a particular ownership result is a thing that's built in.

**Comment by ketralnis** [comment]
Incidentally, I'm willing to use Kafka 0.9 and [the docs for the Java client](https://people.apache.org/~nehanarkhede/kafka-0.9-consumer-javadoc/doc/org/apache/kafka/clients/consumer/KafkaConsumer.html) (search for "This example demonstrates how to rewind the offsets of the entire consumer group ") seem to indicate that the New Consumer API supports this operation. I'm having trouble matching up the vocabulary in their example code to equivalent terms in `managedbalancedconsumer.py`. Should I expect it to or is it not fully implemented?

**Comment by emmett9001** [comment]
Looking more deeply into the `BalancedConsumer` code, I don't actually think there's any way to do what you're asking for with pykafka. An issue in the `BalancedConsumer` is that the [`_decide_partitions`](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L420) function doesn't know how to do anything other than use the standard balancing algorithm to get its partitions. Thus, if any consumer that wants to temporarily take hold of all partitions does so and triggers the watch functions of the other consumers in the group, those other consumers will still decide to keep their standard set of partitions, causing the overwriting issue you mentioned.

This problem also seems to apply to the `ManagedBalancedConsumer`, since it uses the same `_decide_partitions`, but it's possible this functionality would be easier to add to that class since the partition assignment is completely decided by a single consumer, the leader. If there was a way to guarantee that a given consumer would become the group leader, that could be used to set an overriding partition assignment like we're talking about here.

In the meantime, a workaround we use for this at Parsely is to redeploy the entire consumer group with the `reset_offset_on_start=True` flag.

**Comment by emmett9001** [comment]
Also to your point:

> looking at the consumer rebalance algorithm it doesn't look like "insisting" on a particular ownership result is a thing that's built in

I agree that, at least in my experience using Kafka, the behavior you're looking for is nonstandard. I'd love to get more information on exactly what the Java client example you posted is actually doing, since I would have guessed it wasn't possible without some major hackery.

**Comment by emmett9001** [comment]
The example given [above](https://people.apache.org/~nehanarkhede/kafka-0.9-consumer-javadoc/doc/org/apache/kafka/clients/consumer/KafkaConsumer.html) ("rewind the offsets of the entire consumer group") actually requires configuring each consumer in the group with rollback logic, and does not indicate that resetting offsets for the entire group is possible from a single process as @ketralnis is trying to do. The basic reason for this is that any consumer not configured to reset its offsets on start/rebalance will run the configured partition ownership algorithm and take the partitions it thinks it needs.

As for forcibly gaining control of the entire partition set for this purpose, I think that's out of scope for PyKafka. A workaround for anyone looking to do something like this is to "bounce" the entire group of consumer instances with `reset_offset_on_start` and `auto_offset_reset` enabled. Any more detailed operations along these lines should probably be treated as an ops issue with manual intervention via Kazoo/ZooKeeper manipulation.

**Comment by ketralnis** [comment]
Thanks for following up on this! I totally understand pushing it to being out of scope

For those finding this via Google later, I did have a workaround which is to implement zookeeper watches to pass the reset requests down to the consumers that do own the partitions. The details:

I set up a directory in zookeeper with a structure like

    /reset-watches/my-consumer-group/my-topic/1
    /reset-watches/my-consumer-group/my-topic/2
    ...

Where names of the nodes (`1` and `2` above) are a Kafka partition number and the value of that ZK node is what offset I want them to reset to (or empty if there are no pending requests). Then each consumer sets up watches for every node that corresponds to the Kafka partitions that they own and sets the rebalance callback to update its watch list. When the watches trigger they read the new offset from the value of the node and because they own the partitions they are able to reset them normally using `consumer.reset_offsets` and empty out the watched node.

Implementing this safely requires getting the ZK transaction semantics right to deal with race conditions between all of the events that can occur (new reset requests being created, rebalances, completed reset requests, updating the ZK node to reflect that it's done) and may need to be changed for different tradeoffs of how often these rewinds need to happen, tolerance for reprocessing the same message, etc.
