### ISSUE TITLE
Fetcher thread will cause high cpu usage when queues of partitions are full.

### ISSUE THREAD

**Issue by fortime** [Parsely/pykafka#581]
If queues of all owned partitions are full, no fetch requests will be generated. [This codes will be skipped](https://github.com/Parsely/pykafka/blob/39bcf26f04f44c376c0f27074052504185dfa6f6/pykafka/simpleconsumer.py#L730-L733). And finally, `fetch` does nothing. So the fetcher thread will run `fetch` 10,000 times per second.
I don't know if it is your expected behavior.

Steps:
1. create a consumer with queued_max_messages=1.
2. start the consumer without consuming.
3. send messages to make all queues full.
4. run top to monitor cpu usage.

**Comment by emmett9001** [comment]
Thanks @fortime. This is not the same as #470, but similar.

**Comment by emmett9001** [comment]
Naively, this is the expected behavior when the queue is empty, since the kafka protocol dictates that consumers pull new messages from the broker with repeated polling rather than providing some kind of push notification or hook to the consumer. There is certainly an argument for slowing down polling when the internal queue is full, especially since the queue size is user-configurable.

**Comment by emmett9001** [comment]
@fortime Please give #585 a try and let me know if it works for you.
