### ISSUE TITLE
Looking for best practice tips

### ISSUE THREAD

**Issue by arvind-kalyan** [Parsely/pykafka#608]
Hi, 

We're using pykafka in production for our analytics systems, and have found it good. We were using kafka-python earlier, found issues with MultiKafkaConsumer and also data loss issues. 

I wanted to get some advice from the community. The use case is something like this: A single input topic and multiple output topics. The consumer will consume from the input topic, do a bunch of stuff and delegate it to a producer which puts them into corresponding output topic. 

We want to have an array of Kafka producers, which will pick an event E, classify it into E1, E2 etc., do a bunch of transformations and put them into individual event topics. Eg. The input topic is a clickstream topic where all events come in, and from there all login events go to a login topic, all signup events go to a signup topic, etc. How to do this efficiently?

Also is it a good practice to do `with topic.get_producer() as producer` each time we want to produce an event from a running stream of events? 

Right now, we're doing something like this:

```
producer = topic.get_producer
def send(event):
      producer.produce(event)
```

, where send() is called by a consumer constantly consuming events. Here the single producer object is used for sending all the events. 

Hoping for some help here, 
Thanks!

**Comment by emmett9001** [comment]
Hi @arvind-kalyan, and thanks for checking out pykafka. I'd recommend keeping one producer per topic around for the lifetime of your program. Calling `get_producer` is a bit expensive both in terms of cpu and memory, since it allocates a bunch of new resources that the newly created producer requires. Something like this is probably closer to what you want:
```python
topic_producers = {topic.name: topic.get_producer() for topic in topics_to_produce_to}
for destination_topic, message in consumed_messages:
    topic_producers[destination_topic.name].produce(message)
```
If you have additional questions, please feel free to ask on the [user group](https://groups.google.com/forum/#!forum/pykafka-user) or on this issue. Thanks!

**Comment by messense** [comment]
Would be great to have some more best practice tips in the documentation.

**Comment by arvind-kalyan** [comment]
Thanks @emmett9001
