### ISSUE TITLE
Have a way to make build fail if rdkafka dependency isn't built. 

### ISSUE THREAD

**Issue by tdhopper** [Parsely/pykafka#617]
I've been having a hard time getting the rdkafka backend to work with Streamparse (see [this](https://github.com/Parsely/streamparse/issues/280). I think part of my problem is a result of Pykafka not always building the rdkafka extension. I don't love the install [failing so quietly](https://github.com/Parsely/pykafka/blob/1b946fa288dd5eb278f397e858e887146e048e47/setup.py#L164-L172) when the rdkafka extension fails to build. 

I would love a way to make my pip installs fail if the rdkafka extension doesn't build. Perhaps the setuptools Extras notation could be used somehow? `pip install pykafka[rdkafka]`?

**Comment by emmett9001** [comment]
Thanks @tdhopper, I think an optional installation mode like this makes sense to add.

**Comment by tdhopper** [comment]
I've never written anything with an extra in setuptools. If I can figure it out, I'll do a PR.

**Comment by emmett9001** [comment]
As of `2.7.0.dev1`, the installation avoids building the rdkafka extension on platforms other than cpython, which makes this a lot less of an issue for many users. I'm going to close this out, since there hasn't been much additional interest in going further with the installation restrictions, and there are a bunch of safeguards now in place in the code that fail early if rdkafka is not present.
