### ISSUE TITLE
Producer deadlocks when queues are full

### ISSUE THREAD

**Issue by emmett9001** [Parsely/pykafka#641]
Steps to reproduce:

* Run a local 3-node kafka cluster, make a topic with 10 partitions and replication factor 2
* Run a producer producing messages to this topic in a `while True` loop with `max_queued_messages=5`
* Kill two of the kafka nodes
* Observe that the producer deadlocks after repeated retries

This may be related to https://github.com/Parsely/pykafka/pull/633#issuecomment-269578948

**PyKafka version**: https://github.com/Parsely/pykafka/commit/2cabc71b7def03e6a90dfbf767e34e6a8df54bbc
**Kafka version**: 0.9.0.1

**Comment by fxsjy** [comment]
@emmett9001 ,  I also reproduced the bug you described in the issue .
I found that the root cause is:  `self._cluster.update()` did not throw the exception after 3 times of retries. 
Therefore, I add two lines of code in `cluster.py` to raise the exception when retries reach the limit.
https://github.com/Parsely/pykafka/pull/642

Also, I checked the effect of my patches by making two scenarios.
1) Kill two kafka nodes
2) Kill only-one kafka node

For the first scenario,  the producer script will end with an exception raised.
For the second scenario, we can see the "Updating attempt" logs, and the producer script works well.

**Comment by emmett9001** [comment]
Thanks @fxsjy. Are you testing with a replication factor of 3?

**Comment by fxsjy** [comment]
@emmett9001 ,  I have tested it with replication factor of 3.
The producer worked well when I killed two nodes. And, after I killed the last node, the producer script raise an exception.

**Comment by emmett9001** [comment]
Possibly related to #673

**Comment by emmett9001** [comment]
I can't replicate this issue locally on current master. Thanks again @fxsjy, and please post here if this resurfaces in your tests.
