### ISSUE TITLE
How to pin broker API version for non-librdkafka?

### ISSUE THREAD

**Issue by jeffwidman** [Parsely/pykafka#644]
We're using `2.5.0.dev1` in production. 

I'd like to pin the broker version as we're about to upgrade our kafka cluster, and want to make sure that's fully stable before slowly letting the clients talk the new protocol version.

How do I pin the pykafka balancedconsumer / producer? 

I see in the docs there's a `broker_version`, but https://github.com/Parsely/pykafka/releases/tag/2.5.0.dev1 shows that the param is only useful when using `librdkafka`, which we're not using.

**Comment by emmett9001** [comment]
Hi @jeffwidman, and thanks for reaching out. It sounds like you're asking for a way to make pykafka communicate with a newer broker using an older protocol version - for example, talking to a 0.10 broker using the 0.9 protocol. To my knowledge this is not possible. The protocol version used by a broker is defined entirely by the version of kafka that broker is running, and I'm not aware of any mechanism that lets brokers communicate using a different protocol version.

The [versioned changes](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol) to the protocol have so far been backward-compatible with previous versions, which is why our [test suite](https://travis-ci.org/Parsely/pykafka/builds/190323693) succeeds against both kafka 0.8 and 0.10 without needing to tell pykafka itself about which broker version it's communicating with. In fact, with the exception of components using librdkafka, pykafka is as a rule totally unaware of the protocol version of the broker it's talking to.

I hope this helps shed some light on the issue. Please follow up on this ticket if I've missed something - otherwise you can just close it.

**Comment by jeffwidman** [comment]
Yes, I'd like to restrict the version of the API calls that pykafka uses. It's less about exactly 0.9 protocol vs 0.10, but instead a few specific API calls that have multiple versions. 

The issue that I'm trying to avoid is this: https://kafka.apache.org/documentation/#upgrade_10_performance_impact

We upgraded our Kafka clusters from 0.8.2.1 to 0.10.0.1, but most of our consumers use older libraries that do not support the new message format. So we set the brokers' `log.message.format.version` to 0.8.2 while we work on upgrading our consumers. 

In the meantime, I'm worried about a performance problem with consumers that have upgraded and are requesting messages using the new Kafka 10 versions of those API calls. I may be misunderstanding, but it seems logical that the performance problem isn't just about old consumers with a new broker. I would think the performance problem would also exist if we take new brokers, set the log format to an old version, then have our consumers make API calls using the Kafka 10 API calls. The broker would need to do on-the-fly conversion from the 0.8.2 log format up to the 0.10.0 format to send to the new consumers. So as we upgraded consumers, we were planning to pin them to old API versions until all our code was upgraded, then we could just flip the broker log format version and the consumer's broker API version at the same time.

**Comment by emmett9001** [comment]
Thanks for clarifying. Pykafka actually [doesn't yet support](https://github.com/Parsely/pykafka/blob/fb9d9191bc2467ecd0b546eba2e24219b35d4d46/pykafka/protocol.py#L132) the 0.10 log message format, so it sounds like it's in the same situation as most of your other consumers. Also, if I understand correctly, you could deploy a version of pykafka that understands the new message format (which doesn't yet exist) without having to change anything about your setup, since you've set the message format to 0.8.

If you're interested in helping add support for the new message format, please feel free to open a pull request.

**Comment by jeffwidman** [comment]
> Pykafka actually doesn't yet support the 0.10 log message format, so it sounds like it's in the same situation as most of your other consumers. 

Great!

> Also, if I understand correctly, you could deploy a version of pykafka that understands the new message format (which doesn't yet exist) without having to change anything about your setup, since you've set the message format to 0.8.

The new version would request the message using the kafka 0.10 format protocol, so I think the kafka broker would have to convert the messages to that format... essentially I think it'd be inserting `None` into timestamp value, so it should be a fairly inexpensive conversion, but I'm not sure enough on the implementation details.

Thanks again!
