### ISSUE TITLE
How to resolve InconsistentGroupProtocol

### ISSUE THREAD

**Issue by jmwri** [Parsely/pykafka#655]
Hi, we are migrating some of our consumers to golang for increased performance but still need to have pykafka consumers in the same consumer group.

When trying to join the group I am getting InconsistentGroupProtocol exceptions until I stop the GO consumers, in which case pykafka consumers can join the group and start. The same happens the other way around if the pykafka consumers are already started and we start the GO consumers - the GO consumers will throw a similar error and work when we stop the python consumers.

We are using [sarama](https://github.com/Shopify/sarama) and [sarama-cluster](https://github.com/bsm/sarama-cluster) for our GO consumers.

I have tested this with pykafka 2.6.0.dev2.
We are using Kafka 0.10.0.1

Could you give any insight on different group protocols, and whether or not it is possible to change these? Am I right in thinking that there are currently 2 versions of the protocol?

I have used [these docs](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-GroupMembershipAPI) to try to gain an understanding of what is happening.

**Comment by emmett9001** [comment]
According to the [protocol documentation](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-GroupMembershipAPI), `InconsistentGroupProtocolCode` is

> returned in join group when the member provides a protocol type or set of protocols which is not compatible with the current group.

Kafka 0.10's `SyncGroupRequest` is intentionally generic to allow future extensibility. To this end, the [`MemberAssignment`](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-SyncGroupRequest) field in `SyncGroupRequest` is specified as a raw bytestring rather than providing explicit definitions for each of the fields necessary for a partition assignment. The protocol documentation stipulates that all client implementations using the "consumer" protocol type should support the schema it specifies for `MemberAssignment`. PyKafka uses the ["consumer" protocol type](https://github.com/Parsely/pykafka/blob/5345019ef3a66c1c93d0c05f4d3504045324e5c6/pykafka/protocol.py#L1256) and adheres to the standard `MemberAssignment` schema.

From my read of the golang client code you're using, it looks like you're probably [also using](https://github.com/Parsely/pykafka/blob/5345019ef3a66c1c93d0c05f4d3504045324e5c6/pykafka/protocol.py#L1256) the "consumer" protocol type (though bear in mind that I have zero experience with golang). Assuming that's correct, I'm not sure what about these protocol definitions Kafka sees as mismatching. I'm guessing Kafka compares the `ProtocolType` strings of each consumer attempting to join a group, so maybe the golang consumer's `ProtocolType` is not a bytestring, but some unicode representation? That's a bit of a stretch perhaps.

For reference, [this](https://github.com/Parsely/pykafka/blob/5345019ef3a66c1c93d0c05f4d3504045324e5c6/pykafka/protocol.py#L1357) is pykafka's `MemberAssignment` implementation, and [this](https://github.com/Parsely/pykafka/blob/5345019ef3a66c1c93d0c05f4d3504045324e5c6/pykafka/protocol.py#L1198) is its `ConsumerGroupProtocolMetadata` implementation, sent along with `JoinGroupRequest`s.

The central question here is: what aspect of sarama and pykafka's protocol definitions does Kafka see as incompatible?

**Comment by emmett9001** [comment]
Pykafka's [partition assignment logic](https://github.com/Parsely/pykafka/blob/ceb6c9c1700b7c927e2077c66f9c31205bb2890f/pykafka/balancedconsumer.py#L431-L452) was last updated prior to the standardization of different assignment strategies, around version `0.8.2`. It follows the "rebalancing algorithm" laid out [here](https://kafka.apache.org/documentation/#impl_consumerrebalance), which until 0.10 was the only standard strategy available. From my read of the `roundrobin` and `range` strategy documentation, it appears that this algorithm is the `range` strategy. If that's indeed the case, we can simply change `pykafkaassignmentstrategy` to `range` and this problem will probably disappear. If the algorithms are subtly different, we may end up with some partition contention between pykafka and the golang consumers. Support for `roundrobin` can be added in the future, but is not strictly a blocker for using pykafka alongside other consumer implementations.

**Comment by emmett9001** [comment]
@jmwri @joaodlf Please give #656 a try alongside some golang consumers also using the `range` strategy and let us know here how it goes. If it works well, then pykafka's implementation is likely just the `range` strategy with a different name and we can merge #656.
