### ISSUE TITLE
How to use the partiton class for creating partition programmatically?

### ISSUE THREAD

**Issue by vivk89** [Parsely/pykafka#658]
I am trying to create automatic partitions using partition class but i am not getting any output even though there is no error on excution of the program.

This is the code snippet.I am using kafka_2.11-0.9.0.0

```python
client = KafkaClient(hosts = 'localhost:9092')
client1 = KafkaClient(hosts = 'localhost:9093')
client2 = KafkaClient(hosts = 'localhost:9094')

topic = client.topics['custor'] 
partition.Partition(topic,4,client1,client2,client3)
print(topic.partitions)
```

**Comment by emmett9001** [comment]
Hi @vivk89, and thanks for reaching out. Your code creates a python [`Partition` object](http://pykafka.readthedocs.io/en/latest/api/partition.html) in memory and does not communicate with Kafka brokers after the initial connection set up by `KafkaClient`. It sounds like you might be trying to add partitions to an existing topic on your kafka cluster. For this, you'll want to use the kafka [command-line tools](https://kafka.apache.org/documentation/#quickstart_createtopic) instead of pykafka.
