### ISSUE TITLE
Broker Config

### ISSUE THREAD

**Issue by kariya2** [Parsely/pykafka#660]
Is there any way to set the broker configs using pykafka? Specifically I would like to change log.retention.bytes or log.retention.hours as I am running out of memory 

https://kafka.apache.org/documentation/#brokerconfigs

**Comment by emmett9001** [comment]
Hi @kariya2. Changing the broker configs requires editing on-disk configuration files and restarting the broker service. pykafka doesn't support this, since it's primarily a protocol client. Configuration files are more in the purview of server management tools like Chef or Docker. If you'd like to change `retention.ms` for a particular topic instead of the broker's default, you can use the [kafka-topics.sh](https://www.cloudera.com/documentation/kafka/latest/topics/kafka_command_line.html) command line tool to edit that configuration during runtime.

**Comment by kariya2** [comment]
Thanks, that's very helpful
