### ISSUE TITLE
Get complete status of a consumer

### ISSUE THREAD

**Issue by Akhilvis** [Parsely/pykafka#662]
I need to get a complete status about the topic partition ie, whether the consumers consumed all messages of that partition or not.
Here is my producer.py

```

        with topic.get_producer() as producer:
            for file in list_files:
                url = file.geturl()
                producer.produce(str({'path':url}))

```
Here is my consumer code

```
while(1):
       	consumer_a = topic_obj.get_balanced_consumer(consumer_group=b"charlie",zookeeper_connect="localhost:2181")
	msg=consumer_a.consume()
	while(msg):
        /* Use msg*/
          msg=consumer_a.consume()

```
Along with this i need to check something like _topic.iscompleted()_
How can i do that using pykafka?

**Comment by Akhilvis** [comment]
I need to get a complete status about the topic partition ie, whether the consumers consumed all messages of that partition or not.
Here is my producer.py

```

        with topic.get_producer() as producer:
            for file in list_files:
                url = file.geturl()
                producer.produce(str({'path':url}))

```
Here is my consumer code

```
while(1):
       	consumer_a = topic_obj.get_balanced_consumer(consumer_group=b"charlie",zookeeper_connect="localhost:2181")
	msg=consumer_a.consume()
	while(msg):
        /* Use msg*/
          msg=consumer_a.consume()

```
Along with this i need to check something like _topic.iscompleted()_
How can i do that using pykafka?

**Comment by emmett9001** [comment]
Hi @Akhilvis. You can get the latest available offset for a given partition with
```python
consumer.partitions[0].latest_available_offset() 
```
and you can check the offset of the last message consumed for a partition by accessing a private attribute:
```python
consumer._partitions[consumer.partitions[0]].last_offset_consumed
```
An implementation of `is_completed` based on these calls might look like this
```python
def is_completed(consumer):
    for partition in consumer.partitions:
        if consumer._partitions[partition].last_offset_consumed < partition.latest_available_offset():
            return False
    return True
```
We don't expose `_partitions` in the public API because the particular partition that a given message came from is a detail that Kafka clients prefer to obfuscate. If you're concerned about having consumed all messages from a given partition, your use case probably lends itself to using a single partition, at which point you'd be better off simply comparing `consumer.consume().offset` to `topic_obj.latest_available_offsets()`.
