### ISSUE TITLE
The offset got by pykafka is not match with what stores in zookeeper

### ISSUE THREAD

**Issue by lwmonster** [Parsely/pykafka#679]
I get a topic offset by pykafka as follow:
```    
from pykafka import KafkaClient
import pykafka.cli.kafka_tools  as kafka_tools
hosts = '10.0.0.6:9092'
consumerGroup = 'queryengine'
topicName = 'zc.deviceStatus'

client = KafkaClient(hosts)
topics = client.topics
statusTopic = topics[topicName]

lags = kafka_tools.fetch_consumer_lag(client, statusTopic, consumerGroup)
print topicName, lags
```
result : 
```
zc.deviceStatus {0: (17780933, 17696593)}
####Here 17780890 is logsize, 17696593 is consumed offset
```

then I check the zookeeper offset, it shows:
```
get /consumers/queryengine/offsets/zc.deviceStatus/0
17780915

#### Here consumed offset is 17780915 != 17696593
```

My kafka version is : kafka_2.11-0.8.2.1.jar
I have googled for half day but didn't get clear reason, It seems the offset was stored in two different places.
I found a topic named __consumer_offsets in kafka, but can't read any record.

Any idea?

**Comment by emmett9001** [comment]
@lwmonster Thanks for your question. Since Kafka 0.8.2 (possibly slightly earlier than that) Kafka has stored consumer offsets rather than offloading them to ZooKeeper. Looking at the [broker code](https://github.com/Parsely/pykafka/blob/9680a8056165ce589b2e8146f5b5e5f74189f501/pykafka/broker.py#L315), you'll see a number of functions used to make requests to the Kafka broker to fetch these offsets, like the ones you're using in your example code. PyKafka actually doesn't use the offsets stored in ZooKeeper for anything - my guess is that they're still available to maintain backward compatibility.
