### ISSUE TITLE
Need help with producer blocking forever

### ISSUE THREAD

**Issue by carsonip** [Parsely/pykafka#739]
Hi,

**PyKafka version**: commit d5206629683c376e243af7f3aa6843b551e7ace5
**Kafka version**: 0.10.1.0-0
**Python version**: 2.7.6

My producer is blocked forever and would like to seek help here. I use greenlet in my application. This happens very rarely, but when it happens, it causes any code after the produce() function to not run.

pykafka Config (shared among greenlets):
```
_push_client = KafkaClient(hosts=KAFKA_HOSTS, use_greenlets=True)
_push_topic = _push_client.topics[KAFKA_TOPIC]

def get_push_topic():
    return _push_topic
```

How I use pykafka (in each greenlet):
```
with get_push_topic().get_producer() as producer:
    payload = {...}
    producer.produce(json.dumps(payload))
```

Logs (IP address of broker is masked):
```
INFO:pykafka.producer:Starting new produce worker for broker 0
INFO:pykafka.producer:Blocking until all messages are sent
DEBUG:pykafka.producer:Sending 1 messages to broker 0
WARNING:pykafka.producer:Error encountered when producing to broker -.-.-.-:9092. Retrying.
DEBUG:pykafka.cluster:Updating cluster, attempt 1/3
DEBUG:pykafka.connection:Connecting to -.-.-.-:9092
DEBUG:pykafka.connection:Successfully connected to -.-.-.-:9092
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
INFO:pykafka.cluster:Reconnecting to broker id 0: -.-.-.-:9092
DEBUG:pykafka.connection:Connecting to -.-.-.-:9092
DEBUG:pykafka.connection:Successfully connected to -.-.-.-:9092
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 5 topics
INFO:pykafka.topic:Adding 1 partitions
INFO:pykafka.producer:Starting new produce worker for broker 0
DEBUG:pykafka.producer:Successfully sent 0/1 messages to broker 0
INFO:pykafka.producer:Worker exited for broker -.-.-.-:9092
INFO:pykafka.producer:Blocking until all messages are sent
INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
INFO:pykafka.producer:Worker exited for broker -.-.-.-:9092
```

Observations:

1. Subsequent lines don't run
2. That specific greenlet is still alive

Background info:
1. Applied monkey patch from gevent and gevent_openssl
2. Set socket timeout to 2 minutes `socket.setdefaulttimeout(2*60)`
3. There is also a balancedconsumer running in another greenlet

Questions:

1. Is it ok to share a KafkaClient among greenlets and spawn producers (and produce messages) in each greenlet? Any problem with my setup / usage?
2. Any idea why pykafka exits before all messages are sent?

**Comment by carsonip** [comment]
I have now written a service to read from a shared queue shared among greenlets, then send to kafka. In this way, I only have 1 producer which is inside the service. But I'm still curious to know why pykafka fails occasionally.

**Comment by emmett9001** [comment]
@carsonip Thanks for contributing this issue report - it will be very helpful as we improve pykafka's support for greenlets. The short answer to why the producers you're using occasionally freeze up is that pykafka's gevent support is not battle-tested to the same degree that the threaded version is. Using a single producer instead of multiple is a good way to minimize the likelihood of this blocking behavior manifesting. In theory it shouldn't be a problem to use multiple producers in parallel greenlets, but in practice the current version of the library can have some trouble with this.

**Comment by counsellors** [comment]
I also meet this problem that produce blocking forever, but different conf is that my KafkaClent's flag` use_greenlets=False`. The producer use multiple thread to produce() message in sync.

python-2.7.6
pykafka (2.6.0)

threads:
1. block in function get_delivery_report();
2. block in function OwnedBroker.flush(), the result batch is always [];

dump stack:

```
[Switching to thread 14 (Thread 0x7f3de3fff700 (LWP 32948))]
#0  0x00007f3e4898d593 in select () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) py-up
#8 Frame 0x7f3df80023e0, for file /usr/lib/python2.7/Queue.py, line 177, in get (self=<Queue(unfinished_tasks=48922, queue=<collections.deque at remote 0x7f3e442c3c20>, maxsize=0, all_tasks_done=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f3e442c9410>, acquire=<built-in method acquire of thread.lock object at remote 0x7f3e442c9410>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7f3e442c9410>) at remote 0x7f3e213d4810>, mutex=<thread.lock at remote 0x7f3e442c9410>, not_full=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f3e442c9410>, acquire=<built-in method acquire of thread.lock object at remote 0x7f3e442c9410>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7f3e442c9410>) at remote 0x7f3e213d47d0>, not_empty=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f3e442c9410>, acquire=<built-in method acquire of thread.lock object ...(truncated)
    self.not_empty.wait(remaining)
(gdb) py-up
#12 Frame 0x7f3e3c008c40, for file /tmp/pip-build-y9p3OC/pykafka/pykafka/producer.py, line 359, in get_delivery_report (self=<Producer(_auto_start=True, _topic=<Topic(_partitions={0: <Partition(_leader=<Broker(_connection=<BrokerConnection(_handler=<ThreadingHandler at remote 0x7f3e44303390>, _wrap_socket=<function at remote 0x7f3e442b2320>, _socket=<_socketobject at remote 0x7f3e442c3750>, host='xx.xx.xx.xx', source_host='', source_port=0, _buff=<bytearray at remote 0x7f3e0a6eedb0>, port=9092) at remote 0x7f3e442c6850>, _handler=<...>, _id=4, _source_port=0, _offsets_channel_socket_timeout_ms=10000, _socket_timeout_ms=30000, _req_handlers={}, _port=9092, _source_host='', _ssl_config=None, _buffer_size=1048576, _offsets_channel_req_handler=None, _host='xx.xx.xx.xx', _offsets_channel_connection=None, _req_handler=<RequestHandler(shared=<Shared at remote 0x7f3e44295100>, handler=<...>, t=<Thread(_Thread__ident=139905360983808, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at re...(truncated)
```

questions:

1. Unbelievably, _produce() add message to OwnedBroker.queue, then get_delivery_report() couldn't get msg from the queue immediately.  
2.  I think whether the get_delivery_report() loop need max loop number or not, instead of loop forever.

**Comment by emmett9001** [comment]
@counsellors See [this commit](https://github.com/Parsely/pykafka/commit/a4b6793c655d10d6edfc705445ca11dd07692f70), which added a `pending_timeout_ms` kwarg to the producer. This parameter defines how long `get_delivery_report` should block before raising an error. It sounds like this will fix your issue.

Closing because all issues (aside from long-term improvement of gevent support generally) have been addressed. Please reopen if there's more to say.
