### ISSUE TITLE
ManagedBalancedConsumer unique consumer_group

### ISSUE THREAD

**Issue by djamalouch** [Parsely/pykafka#744]
Hi,

I think it would be great, if the description of the ManagedBalancedConsumer is clarified with respect to the parameter consumer_group. I used the same consumer_group string for different consumer instances on different topics and wondered why the consumers are dropping some messages. It would have saved me a lot of hours, if I had seen the keyword "unique" somewhere in the description.

Apart from that: keep up the great work with this library!

**Comment by emmett9001** [comment]
Hi @djamalouch, I'm glad you're getting some good use out of pykafka. If you used the same consumer group string on consumers consuming from different topics, I'd expect that the messages coming from those consumers wouldn't overlap at all, since they're from different topics. I think I need a bit more explanation of the confusion you had to understand what change needs to be made to the docs.

**Comment by emmett9001** [comment]
I thought this was an issue with pykafka, but actually consumer group names do [have to](https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Group+Example) be unique within a Kafka cluster. I'll update some documentation.

**Comment by emmett9001** [comment]
https://github.com/Parsely/pykafka/commit/60cdff36524e221b458541864c61f6dadbb066f4
