### ISSUE TITLE
Standardize zookeeper host string interface

### ISSUE THREAD

**Issue by zpzhoudev** [Parsely/pykafka#820]
I cloud see them in document:
### pykafka.balancedconsumer.BalancedConsumer
> zookeeper_connect  (str) – Comma-separated (ip1:port1,ip2:port2) strings indicating the zookeeper nodes to which to connect.

### pykafka.client.KafkaClient
> zookeeper_hosts  (str) – KazooClient-formatted string of ZooKeeper hosts to which to connect. If not None, this argument takes precedence over hosts

but i don't know which should be used.

thanks

**Comment by emmett9001** [comment]
Thanks for asking, @zpzhoudev. I agree the interface for specifying zookeeper connections could be a bit clearer. The simple answer to your question is that `KafkaClient(zookeeper_hosts=` can be used alone, without needing to specify `zookeeper_connect` in the `BalancedConsumer` constructor. That's because it's [passed through](https://github.com/Parsely/pykafka/blob/d94bc46d238cd32b00dae2aead49310f455e1005/pykafka/topic.py#L275) to `BalancedConsumer` via `Topic`. The `KafkaClient` kwarg is also used in some situations for initial [discovery](https://github.com/Parsely/pykafka/blob/d94bc46d238cd32b00dae2aead49310f455e1005/pykafka/cluster.py#L321) of the Kafka brokers.

The naming of Zookeeper connection strings in the public interface should be audited and standardized.
