### ISSUE TITLE
Handling connection loss in Topic

### ISSUE THREAD

**Issue by rueberger** [Parsely/pykafka#854]
Sometimes I run into a scenario like this:

```
client = pykafka.KafkaClient(...)
topic = client.topics['test_topic']
latest = topic.latest_available_offset() # raises SocketDisconnectedError
```

In this scenario my general approach would be to reinstantiate the topic `topic = client.topics['test_topic']`. 

However, I'm reasonably confident (have not tested explicitly, but reading between the lines) that this is not always sufficient, and there are cases when the reinstantiated topic still has connection problems. 

Thus I'm now planning to reinstantiate the client as well in this scenario, which hopefully will work.

But I just wanted to check to see if there is a recommended best practice for this scenario.

**Comment by emmett9001** [comment]
In these situations I'd recommend running `client.update_cluster(); topic = client.topics['foo']` instead of reinstantiating the client itself. There are probably still situations in which reinstantiating the client is unavoidable, though the goal is to make `update_cluster()` handle all such scenarios.

Note that if you had a `SimpleConsumer` instance that had lost its connection, calling `consumer.update()` would have essentially the same effect.
