### ISSUE TITLE
Offset 0 is skipped when consuming

### ISSUE THREAD

**Issue by jacopofar** [Parsely/pykafka#881]
I'm trying to read all the rows from a partitioned topic, and noticed that the message with offset 0 at each partition is apparently skipped. After that, every other message comes as expected.

I'm using `pykafka 2.8.0` with `Python 3.7` on macOS.

I use `earliest_available_offset` to get the first offset of every partition (which in my case is always 0)  and pass them to `reset_offsets` to initialize a consumer for each partition.

Reading with `consumer.consume(block=False)` I can get the messages and their offset and cannot see the message at offset 0. Using a tool like [Lenses](https://www.landoop.com/lenses-overview/) I see indeed the message at offset 0 and in the end I get every message except for the three what happen to be at offset 0 in each of the three partition.

I've looked at previous issues and can't find anything about this problem. Also I tried to pass `-1` instead of `0` to `reset offsets` but in that case the consumer simply hang.

<details><summary>minimal code to reproduce the issue</summary>
<p>

```python
from functools import lru_cache
import io
import json
from pathlib import Path
import struct

from fastavro import schemaless_reader
from pykafka import KafkaClient, common


bootstrap_servers = ','.join([
    'broker-01.local:9091',
    'broker-02.local:9091',
    'broker-03.local:9091',
    'broker-04.local:9091',
    'broker-05.local:9091',
])


@lru_cache()
def get_schema(schema_id):
    '''Get the schema object from the FS'''
    cached_file = Path("schema/" + str(schema_id) + ".json")
    if cached_file.is_file():
        f = open(cached_file, 'r')
        ret = json.loads(f.read())
        f.close()
        return ret
    raise IOError('no schema', schema_id)


if __name__ == '__main__':

    client = KafkaClient(hosts=bootstrap_servers)
    topic_obj = list(client.topics.keys())

    topic_consumers = []
    topic = 'data-master-cities'
    consumer = client.topics[
        topic.encode('utf8')
    ].get_simple_consumer(
        auto_offset_reset=common.OffsetType.EARLIEST,
        # We go read-only, avoid side effects
        reset_offset_on_fetch=False,
        auto_commit_enable=False
    )

    partition_offset_pairs = []
    for p_index, p in consumer.partitions.items():
        # just start from the beginning
        first_offset = p.earliest_available_offset()
        print('For the partition', p_index, ' initial offset: ', first_offset)
        partition_offset_pairs.append((p, first_offset))
    print('partition offset pairs for topic', topic, partition_offset_pairs)
    consumer.reset_offsets(partition_offsets=partition_offset_pairs)
    topic_consumers.append((topic, consumer))

    print('All the consumers are ready, start consuming from Kafka')
    while True:
        for topic, consumer in topic_consumers:
            message = consumer.consume(block=False)
            if message is not None:
                magic, schema_id = struct.unpack('>bI', message.value[:5])
                schema = get_schema(schema_id)
                payload = schemaless_reader(
                    io.BytesIO(message.value[5:]),
                    schema)

                with open(f'cities_{message.partition_id}.jsonl', 'a') as f:
                    f.write(f'{message.offset} \n')
                    f.write(json.dumps(payload))
                    f.write('\n')

```

This produces

```
For the partition 2  initial offset:  0
For the partition 1  initial offset:  0
For the partition 0  initial offset:  0
partition offset pairs for topic data-master-cities [(<pykafka.partition.Partition at 0x10ec43588 (id=2)>, 0), (<pykafka.partition.Partition at 0x10e49d9e8 (id=1)>, 0), (<pykafka.partition.Partition at 0x10e49d978 (id=0)>, 0)]
```

and then I interrupt the program and in the files I see they contain everything I can see on Lenses, with the same order, except for the three messages at offset 0.
</p>
</details>

**Comment by emmett9001** [comment]
Thanks for the report @jacopofar. What happens if instead of setting `auto_offset_reset` or calling `reset_offsets` explicitly, you simply start a fresh consumer with default values and consume from it? I'm trying to figure out if this is an issue with `reset_offsets` or the consumer more fundamentally.

**Comment by jacopofar** [comment]
OK, I tried and in fact if I don't call `reset_offsets` it starts from offset 0 and I see the very first row, both with `auto_offset_reset` left as is or commented out.

Meanwhile I tried with `confluent-kafka` suspecting it was a problem with librdkafka and there I don't fine the same problem, but noticed that enabling logging I get this warning:

    `Broker version is too old to use automatic API version discovery. Falling back to hardcoded versions list.`

my broker version seems to be `0.8.0`

**Comment by emmett9001** [comment]
That's good that there's a workaround for your situation. I think the `reset_offsets` issue stems from the fact that it treats the given offset as the [last offset consumed](https://github.com/Parsely/pykafka/blob/5c9d594ca9d73a917e6a22adbcea65b34179ba55/pykafka/simpleconsumer.py#L915) for the partition, not the next offset to consume. When trying to set "next offset" to 0 by passing 0 to `reset_offsets`, you're actually setting "next offset" to 1. When you pass -1, you're inadventently using a "magic offset" value that represents the last message on the topic. I recommend passing `pykafka.OffsetType.EARLIEST` to `reset_offsets`, since that's the magic value representing the first message on the partition.

That warning is an expected part of using pykafka with broker versions older than 0.10. Those old brokers don't support automatic api version discovery, so some of pykafka's initialization steps won't work properly without supplying a broker version explicitly.
