### ISSUE TITLE
balanced_consumer using #partitions threads 

### ISSUE THREAD

**Issue by Gaturron** [Parsely/pykafka#892]
First of all, Thanks for all you guys for this great client! It's notable the efford that each one have coding it.

Now the question: Is there any way to config a balanced_consumer that lanched N threads where N is the number of partition of the topic? I mean this is the best configuration for consuming a topic correctly. And perhaps it is a good enhancement to have it already coded. Also, I think that Java client have this setting.

Otherwise you have to make N python producers by your own. That's what I'm doing right now.

**PyKafka version**: 2.8.0
**Kafka version**: 0.8.2.2

**Comment by emmett9001** [comment]
Thanks for the support and feedback, @Gaturron. I'm having a bit of a hard time parsing your question. The `BalancedConsumer` class has a keyword argument `num_fetcher_threads` that can be used to control the number of threads making fetch requests to the consumer's partitions. However, there isn't a way to ensure that each thread makes requests for different partitions. Are you looking for a way to make a consumer with exactly one fetcher thread per partition? If you are, I'm afraid pykafka doesn't currently support this.

**Comment by Gaturron** [comment]
Yes, I tried to do it using the following pseudocode. I showed this just to clarify, perhaps it's useful for someone.
```
def create_and_consume():
     client = KafkaClient(hosts=brokers_conf, broker_version="0.8.2.2")
     topic = client.topics[topic_conf]

     balanced_consumer = topic.get_balanced_consumer(
          consumer_group=group_id_conf,
          auto_commit_enable = True,
          zookeeper_connect=zookeepers_conf
     )
     for msg in balanced_consumer:
          do_something(msg)

processes = []
for i in range(0, num_partitions):
     p = Process(taget=create_and_consume, daemon=True)
     p.start()
     processes.append(p)

for p in processes:
     p.join()
```
Please tell me if balanced consumer works properly in this scenario. Actually I have some issues about the lag. It's not consuming fast as I expeceted but this is another story. Thanks in advance!

**Comment by emmett9001** [comment]
What you're doing here should work, though it's important to keep in mind that the total throughput of this set of consumers will be limited by the power of the machine running all of these processes. This includes metrics like network bandwidth, processor speed, and disk access speed. Because of this, the typical balanced consumption pattern involves using multiple different machines to run multiple consumers. Because balanced consumers can consume more than one partition at a time, you don't really gain much by splitting consumption of the entire topic over multiple processes like you've done in your example. Unless there's some reason you need each partition to be consumed by a separate process, you'd get a very similar result by simply subscribing a single `BalancedConsumer` to the entire topic.
