### ISSUE TITLE
Starting consumer in django

### ISSUE THREAD

**Issue by kyao-Frndz** [Parsely/pykafka#916]
Hi @emmett9001,

We are having problems starting consumers in django. Once consumers have been started (in django's wsgi.py file) all subsequent http request to the application consuming data results in a gateway timeout. 

Can you suggest a better way starting the consumers in django?

**Comment by emmett9001** [comment]
Thanks for the question, @kyao-Frndz. I'm not sure that within a Django application is the best place to run your Pykafka consumers. Since Django is focused on a request/response cycle, it's tough to set up a long-lived object like a consumer such that it will persist across any number of requests. One thing you could try is spawning a separate thread and running the consumer from within it. You might also consider running your consumer on a separate server and communicating with that server via something like `rq`.

**Comment by kyao-Frndz** [comment]
I appreciate your response @emmett9001, thanks a bunch.
