### ISSUE TITLE
pykafka witth librdkafka

### ISSUE THREAD

**Issue by ananthmeka** [Parsely/pykafka#926]

**Comment by carsonip** [comment]
I am about to add notes about the librdkafka setup. It is recommended to use librdkafka v0.9.5 at the moment. librdkafka versions lower than 0.9.1 may fail pykafka pip install silently. There are also some issues with librdkafka v0.11.3+ due to this commit: https://github.com/edenhill/librdkafka/commit/cc43f451b46e41fc3ce00e3b4e5c9bafd11f7b0e

Workaround:
1. Please clone the repo and compile librdkafka: https://github.com/edenhill/librdkafka/tree/v0.9.5
The steps would look like this (I didn't try it, please let me know if it doesn't work):
```bash
git clone https://github.com/edenhill/librdkafka
cd librdkafka
git checkout v0.9.5
./configure
make
sudo make install
sudo ldconfig
```

2. pykafka setup will setup without librdkafka extension if the compilation fails. pip install will silent `print` statements in setup.py. Therefore, you won't see any error messages. If you want to confirm that the librdkafka extension is compiled successfully, use `pip install -v pykafka` and make sure that you don't see "Failed to build rdkafka extension". If you see any error messages, feel free to post them here.

Things will get better after #920 is resolved.

**Comment by ananthmeka** [comment]
Thank you , Since my initial setup was not having the gcc and g++ , tried with pip install way. since it was not working , installed the required build utils and built the liibrdkafka and pykafka and able to use the pykafka with rdkafka now
