### ISSUE TITLE
Bi-direct communication handle in kafka

### ISSUE THREAD

**Issue by teguh87** [Parsely/pykafka#930]
Hai I need to know how pykafka handle bi-direct message, ex: if producer sending message and consumer received and send back to producer to the origin topic.

**Comment by emmett9001** [comment]
Hi @teguh87, and thanks for the question. I'm afraid you'll need to be a bit more precise about what you're looking for, since the notion of sending a message "to a producer" doesn't really exist in Kafka's semantic model. It sounds like you might be interested in consuming a message from a topic without "removing" it from the topic, in which case you might look into performing manual offset commits based on when you're "done with" the message. Or, if you're talking about implementing bidirectional communication between two servers, you'd want to put a producer and a consumer instance on each of those servers. Each consumer might consume a different topic, and each producer might produce to one of those topics.

These are just some vague ideas, though. I'd also recommend asking this question on the [Kafka users mailing list](mailto:users@kafka.apache.org).
